import test from 'node:test';
import assert from 'node:assert/strict';
import {FishingGame,floatMarks} from '../src/engine.js';
import {newPlayer,validateSave,savePlayer,loadPlayer,SAVE_KEY} from '../src/save.js';

function advanceUntil(g,predicate,max=50){for(let i=0;i<max*10;i++){g.step(.1);if(predicate())return;}assert.fail(`Timed out: ${g.phase} — ${g.message}`);}
function land(g){assert.ok(g.cast());advanceUntil(g,()=>g.phase==='bite');assert.ok(g.strike());advanceUntil(g,()=>{if(g.tension>78)g.ease();else if(!g.surge)g.pulling=true;return g.phase==='landed';},60);}

test('Fish exist before casting; the bite and catch retain the same instance',()=>{const p=newPlayer(),g=new FishingGame(p,{seed:22});const before=new Set(g.fish.map(f=>f.id));land(g);assert.ok(before.has(g.hooked.id));assert.ok(g.hooked.caught);assert.equal(p.catches,1);assert.equal(p.collection[p.pending.fishId].count,1);});
test('A catch can credit the wallet once, including after save/reload',()=>{const p=newPlayer(),g=new FishingGame(p,{seed:4});land(g);const saved=validateSave(JSON.parse(JSON.stringify(p))),restored=new FishingGame(saved);const {id,value}=saved.pending,start=saved.coins;assert.ok(restored.resolveCatch(id,'sell'));assert.equal(saved.coins,start+value);assert.equal(restored.resolveCatch(id,'sell'),false);assert.equal(saved.coins,start+value);assert.equal(saved.sold,1);});
test('Release preserves the journal and never credits sale value',()=>{const p=newPlayer(),g=new FishingGame(p,{seed:19}),start=p.coins;land(g);const id=p.pending.id;assert.ok(g.resolveCatch(id,'release'));assert.equal(p.coins,start);assert.equal(p.released,1);assert.equal(Object.keys(p.collection).length,1);assert.equal(g.resolveCatch(id,'release'),false);});
test('An early strike fails and consumes exactly one portion of bait',()=>{const p=newPlayer(),g=new FishingGame(p,{seed:5}),start=p.baits.worm;g.cast();assert.equal(g.strike(),false);assert.equal(g.phase,'failed');assert.equal(p.baits.worm,start-1);assert.equal(p.catches,0);});
test('No compatible bait/depth means no spawned bite',()=>{const p=newPlayer();p.rig.depth=.4;p.bait='corn';const g=new FishingGame(p,{seed:1});g.cast();advanceUntil(g,()=>g.phase==='failed',40);assert.equal(p.catches,0);assert.equal(g.hooked,null);});
test('An unbalanced rig cannot cast or spend bait',()=>{const p=newPlayer(),g=new FishingGame(p);p.rig.lead=1.5;const before=p.baits.worm;assert.equal(floatMarks(p),0);assert.equal(g.cast(),false);assert.equal(p.baits.worm,before);});
test('Pulling continuously on a large fish can break the line',()=>{const p=newPlayer(),g=new FishingGame(p,{seed:1});g.cast();advanceUntil(g,()=>g.phase==='bite');g.strike();g.hooked.weight=2.4;g.pulling=true;advanceUntil(g,()=>g.phase==='failed',20);assert.match(g.message,/Đứt dây/);assert.equal(p.pending,null);});
test('Paused simulation preserves the strike window and deadline',()=>{const p=newPlayer();p.settings.deadline=180;const g=new FishingGame(p,{seed:6});g.cast();advanceUntil(g,()=>g.phase==='bite');const elapsed=g.elapsed;g.paused=true;for(let i=0;i<400;i++)g.step(.1);assert.equal(g.phase,'bite');assert.equal(g.elapsed,elapsed);g.paused=false;g.strike();assert.equal(g.phase,'fight');});
test('Empty wallet and bait can recover with the free starter kit',()=>{const p=newPlayer();p.coins=0;p.baits.worm=0;const g=new FishingGame(p,{seed:3});assert.equal(g.cast(),false);assert.ok(g.digWorms());assert.equal(p.baits.worm,6);assert.ok(g.cast());});
test('Shop purchases and lesson rewards are atomic and idempotent',()=>{const p=newPlayer(),g=new FishingGame(p);p.coins=50000;assert.ok(g.buy('rod','dai'));assert.equal(p.coins,5000);assert.equal(g.buy('rod','dai'),false);assert.ok(g.answerLesson('signal',0));assert.equal(p.coins,7500);assert.ok(g.answerLesson('signal',0));assert.equal(p.coins,7500);assert.equal(g.answerLesson('depth',0),false);});
test('Lure needs retrieve input before fish approach and does not consume bait',()=>{const p=newPlayer();p.rods.push('spinning');p.rod='spinning';p.bait='lure';const g=new FishingGame(p,{seed:12});g.cast();for(let i=0;i<100;i++)g.step(.1);assert.equal(g.target,null);g.toggleRetrieve();advanceUntil(g,()=>g.phase==='bite');assert.equal(g.target.fishId,'fish_04');assert.equal(p.baits.worm,18);});
test('Deadline stops active fishing and a new session resumes',()=>{const p=newPlayer();p.settings.deadline=180;const g=new FishingGame(p);g.elapsed=179.95;g.cast();g.step(.1);assert.ok(g.deadlineReached);assert.equal(g.cast(),false);assert.ok(g.newSession());assert.equal(g.deadlineReached,false);assert.equal(g.elapsed,0);});
test('Broken saves and blocked storage safely report a new session',()=>{const storage={getItem:()=>'{broken',setItem:()=>{throw Error('blocked');}};const result=loadPlayer(storage);assert.equal(result.player.coins,12000);assert.ok(result.warning);assert.equal(savePlayer(storage,result.player),false);assert.throws(()=>validateSave({...newPlayer(),coins:-10}));});
test('Save roundtrip preserves owned gear, bait, progress and settings',()=>{let raw;const storage={getItem:()=>raw,setItem:(k,v)=>{assert.equal(k,SAVE_KEY);raw=v;}};const p=newPlayer();p.rods.push('dai');p.map='AO';p.lessons.push('signal');p.settings.deadline=300;assert.ok(savePlayer(storage,p));assert.deepEqual(loadPlayer(storage).player,p);});
