import {advanceGarden,gardenAction,gardenTool,gardenSoilReady,GARDEN_DAY,CORN_GROWTH_HOURS} from './garden.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:1}).format(v);
const svg=body=>`<svg viewBox="0 0 160 120" aria-hidden="true">${body}</svg>`;
export function gardenItemArt(item){
 if(item.slot==='hoe')return svg('<path d="M45 106 103 18" stroke="#94703e" stroke-width="10" stroke-linecap="round"/><path d="m82 34 34 14 17-23-31-17Z" fill="#657b70" stroke="#344f43" stroke-width="3"/><path d="m110 12 21 15" stroke="#b6c4ac" stroke-width="3"/>');
 if(item.slot==='water')return svg('<path d="M52 44h54l-4 49H48Z" fill="#7e9980" stroke="#3c5d4a" stroke-width="3"/><path d="M58 42q0-36 37-26l5 26M50 48q-37-8-27 30l25 2" stroke="#49634b" stroke-width="5" fill="none"/><path d="m105 65 27-19 6 11-34 27Z" fill="#789c87" stroke="#3c5d4a" stroke-width="3"/><path d="m138 64 5 6m-10-1 5 8m-12-2 4 8" stroke="#6babad" stroke-width="3" stroke-linecap="round"/>');
 if(item.slot==='dig')return svg('<path d="m45 24 42 38" stroke="#9b743e" stroke-width="13" stroke-linecap="round"/><path d="m76 59 23-15 34 38-1 25-28-4Z" fill="#779182" stroke="#3f5c49" stroke-width="3"/><path d="m95 60 24 29" stroke="#bac8b3" stroke-width="3"/>');
 return svg(`<path d="M51 25h61l-9 16 16 60H40l16-60Z" fill="${item.id==='corn_seed'?'#d3b76b':'#927d56'}" stroke="#6f5f3e" stroke-width="3"/><path d="M53 34h55M59 43h43" stroke="#5d6743" stroke-width="4"/><ellipse cx="78" cy="74" rx="22" ry="21" fill="#f4e4b6"/>${item.id==='corn_seed'?'<path d="m78 59 11 28M68 65l11 23M68 75l20-7M73 84l20-7" stroke="#ba8c34" stroke-width="4"/>':'<path d="M65 81q-4-26 28-25 5 26-23 26m-4 9 17-22" stroke="#557348" stroke-width="3" fill="#83965b"/>'}`);
}
function timeLeft(until,now){const minutes=Math.max(0,Math.ceil((until-now)/60000));return minutes<60?`${minutes} phút`:`${Math.floor(minutes/60)} giờ${minutes%60?' '+minutes%60+' phút':''}`;}
export function gardenPlotArt(g,bed){
 const crop=g.corn.crop,stage=!crop?0:crop.health<=0?-1:crop.progress<12?1:crop.progress<36?2:crop.progress<60?3:4;
 const dirt=g[bed].soil.moisture>=35?'#725c3f':'#ad8b57';
 let plants='';
 if(bed==='corn')for(let row=0;row<2;row++)for(let col=0;col<5;col++){
  const x=70+col*66+row*13,y=146+row*38,h=stage<0?38:stage===1?10:stage===2?38:stage===3?69:84,color=stage<0?'#ad985f':'#557447';
  plants+=stage===0?`<ellipse cx="${x}" cy="${y}" rx="8" ry="3" fill="#493d2b"/>`:`<g transform="translate(${x} ${y})"><path d="M0 0Q${stage<0?20:4} -${h/2} ${stage<0?19:0} -${h}" fill="none" stroke="${color}" stroke-width="4"/><path d="M0 -${h*.3}q-24-28-28-15 8 19 28 23m0-${h*.2}q25-25 31-17-6 21-31 21" fill="${color}"/>${stage===4?'<ellipse cx="8" cy="-40" rx="6" ry="14" fill="#e9c46f" transform="rotate(18 8 -40)"/><path d="m0-78-12-10m12 10 13-12m-13 12v-14" stroke="#cfbd77" stroke-width="2"/>':''}</g>`;
 }
 else{
  plants='<path d="M53 98q95-50 157 1t166-3" stroke="#b59f59" stroke-width="15" fill="none" stroke-dasharray="25 14"/><path d="M76 78q-9-29 16-32 30 1 28 23-34 4-44 9m116 14q-5-32 32-30 19 24-32 30m112-6q-13-25 8-34 32-1 25 27Z" fill="#89945b" stroke="#65724b" stroke-width="2"/>';
  if(g.worms.stock>=1)plants+=Array.from({length:Math.min(5,Math.floor(g.worms.stock))},(_,i)=>`<path d="M${75+i*58} ${152+i%2*14}q12-18 26-1t23 0" fill="none" stroke="#d6a18a" stroke-width="5" stroke-linecap="round"/>`).join('');
 }
 return `<svg class="garden-art" viewBox="0 0 420 230" role="img" aria-label="${bed==='corn'?(stage===0?'Luống ngô chưa gieo':stage<0?'Luống ngô héo':'Ngô đang lớn trong vườn'):'Góc đất phủ lá cho giun'}"><rect width="420" height="230" fill="#dee3c6"/><path d="M0 72q89-36 160-3t260-8v169H0Z" fill="#8c9d6a"/><path d="m23 114 361-17 30 98-366 20Z" fill="${dirt}" stroke="#5b4e34" stroke-width="3"/><path d="m35 134 354-17m-348 45 356-17m-342 43 352-17" stroke="#493e2c" stroke-opacity=".3" stroke-width="5"/>${plants}<path d="M10 211 404 190" stroke="#b7a27b" stroke-width="8"/><g stroke="#927b51" stroke-width="4"><path d="M19 105V46m39 50V39m320 59V45m-369 10 51-8m310 9 35-7"/></g></svg>`;
}
export function renderGarden(player,game){
 const now=game.wallClock(),g=advanceGarden(player.systems.garden,now),away=!game.atHome||game.busy||!!player.pending;
 const action=(id,bed,label,primary=false)=>{const result=gardenAction(g,id,bed,now);return `<button id="garden-${bed}-${id}" data-garden-action="${id}" data-bed="${bed}" class="${primary?'green':''}" ${away||!result.ok?'disabled':''} title="${esc(away?'Về nhà trước khi chăm vườn':result.ok?label:result.reason)}">${label}</button>`;};
 const meters=bed=>`<div class="garden-soil">${[['moisture','Độ ẩm',35],['nutrients','Dinh dưỡng',30],...(bed==='corn'?[['looseness','Độ tơi',40]]:[])].map(([key,label,minimum])=>`<label><span>${label}<b>${Math.floor(g[bed].soil[key])}%</b></span><meter min="0" max="100" low="${minimum}" high="100" optimum="75" value="${g[bed].soil[key]}" aria-label="${label}" title="Cần từ ${minimum}%"></meter><small>Cần từ ${minimum}%</small></label>`).join('')}</div>`;
 const crop=g.corn.crop,dead=crop&&crop.health<=0,ready=crop&&!dead&&crop.progress>=CORN_GROWTH_HOURS;
 const cornNeeds=[g.corn.soil.moisture<35?'nước':'',g.corn.soil.nutrients<30?'phân hữu cơ':'',g.corn.soil.looseness<40?'xới đất / nhổ cỏ':''].filter(Boolean);
 const cornNote=dead?'Cây đã héo. Dọn luống, chăm đất rồi gieo lại.':ready?'Ngô đã chín. Thu hoạch để cất mồi vào kho nhà.':cornNeeds.length?`Cần ${cornNeeds.join(', ')}${crop?'; cây đang ngừng lớn':''}.`:crop?'Ngô đang lớn. Ghé kiểm tra và tưới mỗi ngày.':'Đất đã sẵn sàng. Dùng 1 lượt hạt giống để gieo.';
 const wormWait=g.worms.lastDugAt!==null&&now-g.worms.lastDugAt<GARDEN_DAY;
 const wormNote=wormWait?`Lượt đào tiếp theo sau ${timeLeft(g.worms.lastDugAt+GARDEN_DAY,now)}.`:!gardenSoilReady(g.worms.soil,'worms')?'Giun cần đất đủ ẩm và chất hữu cơ. Tưới, thêm phân rồi để đất nghỉ.':g.worms.stock<3?`Giun đang hồi. Cần thêm khoảng ${number((3-g.worms.stock)*4)} giờ đất tốt để đào.`:'Đã có thể đào. Chỉ lấy một phần, để lại giun trong đất.';
 return `<section class="game-window garden-window"><header class="page-head"><div><p class="eyebrow">Ở NHÀ · GIỜ THẬT</p><h1>Ruộng vườn</h1><p>Chăm đất hôm nay, có mồi cho buổi câu sau.</p></div><a class="button small" href="#home">Về nhà</a></header><p class="garden-intro">Vườn vẫn lớn khi đóng game. Ngô cần 72 giờ đất tốt, giun hồi trong đất ẩm có chất hữu cơ. Ghé chăm mỗi ngày; bỏ chăm sẽ làm cây héo và giun giảm.</p>
 <div class="garden-kit"><div><strong>Đồ nhà có sẵn</strong><small>Dụng cụ ở lại nhà, tự dùng loại tốt nhất.</small></div>${['hoe','water','dig'].map(slot=>{const tool=gardenTool(g,slot);return `<span>${gardenItemArt(tool)}<b>${tool.name}</b></span>`;}).join('')}<button class="small" data-stock="garden">Đồ làm vườn ở Chợ bến</button></div>
 <div class="garden-stock"><span>Hạt giống <b id="garden-seeds">${g.supplies.corn_seed}</b> lượt</span><span>Phân hữu cơ <b id="garden-compost">${g.supplies.compost}</b> phần</span><span>Đã thu <b>${g.harvests.corn}</b> vụ ngô · <b>${g.harvests.worm}</b> lượt giun</span><a href="#rig">Bỏ mồi trong kho vào túi →</a></div>
 <div class="garden-plots"><article class="garden-plot" data-garden-plot="corn">${gardenPlotArt(g,'corn')}<div class="garden-plot-copy"><div class="garden-plot-head"><h2>Luống ngô</h2><span class="pill">${dead?'Héo':ready?'Chín':crop?'Đang lớn':'Chưa gieo'}</span></div>${crop?`<div class="garden-growth"><span>${number(crop.progress)} / 72 giờ đất tốt <b>Sức cây ${Math.round(crop.health)}%</b></span><progress value="${crop.progress}" max="72" aria-label="Sinh trưởng ngô"></progress></div>`:''}${meters('corn')}<p class="garden-next" role="status">${cornNote}</p><div class="garden-care">${action('hoe','corn','Xới đất')}${action('water','corn','Tưới nước')}${action('feed','corn','Bón phân · 1 phần')}</div><div class="garden-main-action">${dead?action('clear','corn','Dọn cây héo'):crop?action('harvest','corn','Thu hoạch ngô',true):action('plant','corn','Gieo ngô · 1 lượt giống',true)}</div></div></article>
 <article class="garden-plot" data-garden-plot="worms">${gardenPlotArt(g,'worms')}<div class="garden-plot-copy"><div class="garden-plot-head"><h2>Góc đất ủ lá</h2><span class="pill">${Math.floor(g.worms.stock)} / 8 phần giun</span></div><p class="garden-worm-guide">Giữ ẩm, thêm chất hữu cơ; tránh cuốc lật góc này. Giun hồi tối đa 8 phần, không tích vô hạn khi bỏ game.</p>${meters('worms')}<p class="garden-next" role="status">${wormNote}</p><div class="garden-care">${action('water','worms','Tưới nước')}${action('feed','worms','Thêm hữu cơ · 1 phần')}</div><div class="garden-main-action">${action('dig','worms',`Đào giun · tối đa ${gardenTool(g,'dig').effect} phần`,true)}</div></div></article></div>
 <section class="garden-composter"><div>${gardenItemArt({id:'compost'})}</div><div><h2>Ủ lá thành phân</h2><p>${g.composter.readyAt!==null?(now>=g.composter.readyAt?'Mẻ ủ đã xong. Nhận 1 phần phân hữu cơ.':`Mẻ ủ còn ${timeLeft(g.composter.readyAt,now)}.`):g.composter.lastStartedAt!==null&&now-g.composter.lastStartedAt<GARDEN_DAY?`Có thể gom lá tiếp sau ${timeLeft(g.composter.lastStartedAt+GARDEN_DAY,now)}.`:'Gom lá khô mỗi 24 giờ, ủ 12 giờ thành 1 phần phân. Không tốn xu; vẫn phải chờ và chăm đất để có mồi.'}</p></div>${g.composter.readyAt!==null?action('collect','composter','Lấy phân hữu cơ',true):action('compost','composter','Gom và ủ lá')}</section>
 <p class="fineprint">Dụng cụ cơ bản, 3 lượt giống và 2 phần phân được cấp một lần khi có vườn. Thu ngô khỏe giữ lại 1 lượt giống. Mồi thu hoạch cất ở kho nhà; mồi bột chỉ mua tại Chợ bến. Thời gian và sản lượng là mô phỏng game.</p></section>`;
}
