import {MAPS,FISH,RODS,BAITS,LESSONS,getMap,getBait} from './content.js';
import {floatMarks,rigError} from './engine.js';
// Presentation only: the simulation, currency and save format remain in their existing modules.
const money=v=>new Intl.NumberFormat('vi-VN').format(v);
const kg=v=>new Intl.NumberFormat('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const paths={
 fish:'M4 12c5-7 12-7 17 0-5 7-12 7-17 0ZM4 12 1 8v8l3-4Zm11-2h.01M9 7l3-4 3 4M9 17l3 4 3-4',
 rod:'M4 21 17 3M17 3q4 4 3 9v5q0 5-4 3v-3M6 17l3 2',
 bag:'M5 7h14l2 14H3L5 7Zm3 0V5a4 4 0 0 1 8 0v2M8 12h8M9 16h6',
 book:'M12 5q-5-3-10 0v15q5-3 10 0 5-3 10 0V5q-5-3-10 0Zm0 0v15M5 9h4M15 9h4M5 13h4M15 13h4',
 collection:'M4 3h16v18H4V3Zm3 4h10M7 17h10M7 12q5-5 10 0-5 5-10 0Zm8-1h.01',
 shop:'M3 9h18l-2-6H5L3 9Zm0 0v2a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0V9M5 14v7h14v-7M9 21v-6h6v6',
 coin:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 6v12M15 8h-5a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H9',
 settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Zm7 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
 pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 1 1 14 0Zm-4 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 lock:'M5 10h14v11H5V10Zm3 0V7a4 4 0 0 1 8 0v3M12 14v3',
 check:'m5 12 4 4L19 6', arrow:'M4 12h16m-6-6 6 6-6 6', play:'m8 4 13 8-13 8V4Z', pause:'M8 4v16M16 4v16',
 help:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM9 8a3 3 0 0 1 6 0c0 3-3 2-3 5M12 17h.01',
 clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 6v6l4 2',
 trophy:'M8 3h8v7a4 4 0 0 1-8 0V3Zm0 2H3v3a4 4 0 0 0 5 4m8-7h5v3a4 4 0 0 1-5 4M12 14v6M7 21h10',
 wave:'M2 8q3-4 6 0t6 0 6 0M2 14q3-4 6 0t6 0 6 0M2 20q3-4 6 0t6 0 6 0',
 target:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-5 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM12 12h.01',
 chevron:'m6 9 6 6 6-6', leaf:'M20 3C9 2 2 8 5 16c8 5 16-2 15-13ZM5 20 16 9',
};
export function icon(name,className=''){return `<svg class="icon ${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||''}"/></svg>`;}
export const NAV_ITEMS=[['fishing','rod','Buổi câu'],['rig','bag','Đồ nghề'],['learn','book','Học câu'],['journal','collection','Sổ cá'],['shop','shop','Chợ bến']];
export function rankFor(catches){
 const ranks=[[0,'Tân thủ'],[5,'Cần thủ ao làng'],[15,'Tay câu vững'],[30,'Lão làng'],[60,'Đại lão câu cá']];
 const i=ranks.findLastIndex(([n])=>catches>=n),start=ranks[i][0],next=ranks[i+1]?.[0];
 return {name:ranks[i][1],count:catches-start,max:next?next-start:1,label:next?`${catches} / ${next} cá`:`${catches} cá · Bậc cao nhất`,complete:!next};
}
export function avatarArt(){return `<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30" fill="#284f40"/><path d="M14 62q0-19 18-19t18 19" fill="#a5956b"/><path d="M23 25h18v12q-2 13-9 13t-9-13" fill="#e8bd83"/><path d="M11 28 32 5l21 23q-22 9-42 0" fill="#e3bd71" stroke="#836335" stroke-width="2"/><path d="M21 27 32 8l11 19M11 28h42" fill="none" stroke="#b48b47" stroke-width="2"/><path d="M27 36h1m8 0h1M28 43q4 3 8 0" stroke="#674e31" stroke-width="2" stroke-linecap="round"/></svg>`;}
export function fishArt(f){
 const dark=f?.color||'#71847c',id=f?.id||'unknown',long=['fish_04','fish_05','fish_07','fish_10'].includes(id),rx=long?65:50,ry=long?17:26;
 const whisker=id==='fish_05'?'<path d="M153 38q17-12 26-3M154 46q22 6 25 18" fill="none" stroke="#655F3E" stroke-width="2"/>':'';
 const stripes=['fish_06','fish_11','fish_12'].includes(id)?'<path d="M76 21l-6 38M92 19l-6 43M108 21l-4 37" stroke="#fff" stroke-opacity=".28" stroke-width="4"/>':'';
 return `<svg viewBox="0 0 200 88" aria-hidden="true"><path d="M${95-rx} 44 15 24 15 64Z" fill="${dark}"/><path d="M76 24 96 9 119 25M81 61l20 14 17-16" fill="${dark}" opacity=".72"/><ellipse cx="98" cy="44" rx="${rx}" ry="${ry}" fill="${dark}"/><path d="M${98-rx+12} 49q45 22 ${rx*2-22} -3" fill="none" stroke="#fff" stroke-opacity=".25" stroke-width="3"/>${stripes}<path d="M140 31q-9 12 0 23" stroke="#183D37" fill="none" opacity=".35"/><circle cx="147" cy="37" r="3.5" fill="#FFFCF5"/><circle cx="148" cy="37" r="1.8" fill="#183D37"/>${whisker}</svg>`;
}
export function toolArt(kind,id=''){
 if(kind==='rod')return `<svg viewBox="0 0 200 130" aria-hidden="true"><path d="M28 111 150 19" stroke="${id==='bamboo'?'#a68248':'#395f53'}" stroke-width="6" stroke-linecap="round"/><path d="m38 104 16-12" stroke="#58482b" stroke-width="9" stroke-linecap="round"/><path d="m75 74 3 3m25-25 3 3m23-22 3 3" stroke="#dfc173" stroke-width="3"/><path d="M150 19q15 5 16 26v58q0 17-13 9v-8" fill="none" stroke="#81978c" stroke-width="1.5"/>${id==='spinning'?'<circle cx="66" cy="94" r="12" fill="#c49b53" stroke="#34574a" stroke-width="4"/><path d="m56 87-8-12m26 26 11 5" stroke="#34574a" stroke-width="4"/>':'<path d="M166 58v22" stroke="#d07240" stroke-width="4"/><path d="M166 64v5m0 5v4" stroke="#efd274" stroke-width="4"/>'}</svg>`;
 return `<svg viewBox="0 0 140 110" aria-hidden="true">${id==='corn'?'<path d="M46 88q-13-48 18-58 29-6 30 25T46 88" fill="#dfb753" stroke="#a38030" stroke-width="2"/><path d="m57 35 17 52M71 31l15 43M48 52l40-12M46 66l45-13M49 80l38-11" stroke="#f9dc87" stroke-width="3"/><path d="M42 65q-17 22 6 35l29-9" fill="#78924e"/>':id==='dough'||id==='cloudbait'?'<path d="M37 91 45 30h50l8 61Z" fill="#d2ad70" stroke="#a5844b" stroke-width="2"/><path d="M43 31q25 9 53 0" stroke="#87734c" fill="none" stroke-width="4"/><circle cx="70" cy="63" r="15" fill="#f2dfb6"/><path d="m58 65 8-9 8 9 7-6" fill="none" stroke="#758459" stroke-width="3"/>':'<path d="M43 79q-26-40 9-40t15 29q-23 24 6 30 31 4 25-21" stroke="#b57d61" fill="none" stroke-width="13" stroke-linecap="round"/><path d="m41 56 10-4m-6-12 9 4m12 10 10 3M64 80l9 7m4 10 1-12" stroke="#e0ab81" stroke-width="3"/>'}</svg>`;
}
export function mapArt(id){return `<svg viewBox="0 0 320 160" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="320" height="160" fill="#d6d5a1"/><path d="M0 45Q80 5 165 38T320 17V160H0" fill="#92aa75"/>${id==='HO'?'<path d="m0 70 65-60 43 41 56-50 72 66 40-43 44 51v50H0Z" fill="#6a8b72"/><path d="m56 19 9-9 17 16-13-4-4 6Z" fill="#e0e3c5"/><ellipse cx="182" cy="123" rx="131" ry="57" fill="#588b82"/>':id==='KENH'?'<path d="M129 0q-30 45 19 65t-4 95h58q48-58-11-100t0-60" fill="#6faaa0"/><path d="M0 54h108M10 82h92M223 74h97M217 101h103M22 126h80" stroke="#c0c28b" stroke-width="8"/>':'<ellipse cx="169" cy="111" rx="140" ry="58" fill="#77a99a"/><path d="M15 76h123M23 66v25m29-26v24m29-24v24m29-24v24" stroke="#a38350" stroke-width="4"/><path d="M228 54h46v32h-46Z" fill="#e8d0a1"/><path d="m217 55 34-23 34 23Z" fill="#a1744b"/>'}<g fill="#3e6b49"><path d="m22 12-17 38h34Zm273 49-15 31h30ZM248 5l-14 30h28Z"/><circle cx="54" cy="39" r="13"/><circle cx="290" cy="118" r="13"/></g><g fill="none" stroke="#b2d2b6" stroke-width="2" opacity=".7"><path d="M127 113h39m19 16h45m-87 16h43"/></g></svg>`;}
function warningHTML(warning){return warning?`<div class="save-warning">${esc(warning)}</div>`:'';}
function heading(kicker,title,copy,action=''){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${copy}</p></div>${action}</div>`;}
function progressLine(value,total){return `<div class="quest-track"><i style="width:${Math.min(100,value/total*100)}%"></i></div>`;}
export function renderHome(player,game,warning){
 const known=Object.keys(player.collection).length,quests=[['Câu con cá đầu tiên',Math.min(player.catches,1),1,'fishing'],['Hoàn thành bài đọc phao',player.lessons.includes('signal')?1:0,1,'learn'],['Khám phá 3 loài cá',Math.min(known,3),3,'journal']];
 return `${warningHTML(warning)}<section class="camp-scene"><img class="camp-bg" src="./assets/ao-lang.webp" alt="Ao làng Việt Nam với cầu tre, người câu cá và những ngôi nhà bên bờ nước"><div class="camp-shade"></div>
 <div class="camp-title"><p class="eyebrow"><span class="little-line"></span> GAME CÂU CÁ VIỆT NAM</p><h1>TRỐN VỢ<br><span>ĐI CÂU!</span></h1><p>Cần tre sẵn rồi.<br>Ra ao làm một buổi thôi!</p><div class="camp-actions"><a class="button primary start-button" href="#fishing">${icon('play')}<span>${player.casts?'TIẾP TỤC BUỔI CÂU':'XÁCH CẦN RA AO'}</span></a><button class="icon-button" id="home-help" aria-label="Cách chơi">${icon('help')}</button></div><button class="mode-button" id="home-mode">${icon('clock')}<span>${player.settings.deadline?`Trốn vợ · ${player.settings.deadline/60} phút`:'Thư thả · Không giới hạn'}</span>${icon('chevron')}</button></div>
 <aside class="quest-board"><div class="board-heading">${icon('target')}<h2>Hành trình cần thủ</h2></div><p class="board-subtitle">Mỗi buổi câu, tiến thêm một chút.</p>${quests.map(([name,value,total,target])=>`<a class="quest ${value===total?'complete':''}" href="#${target}"><span class="quest-mark">${icon(value===total?'check':'target')}</span><span class="quest-copy"><strong>${name}</strong><span class="quest-detail">${value===total?'Đã hoàn thành':`${value} / ${total}`}</span>${progressLine(value,total)}</span></a>`).join('')}<div class="board-footer">${icon('fish')}<span><b>${player.catches}</b> cá đã câu</span><span><b>${known}/12</b> loài</span></div></aside>
 <div class="camp-location">${icon('pin')}<div><strong>${game.map.name}</strong><span>${game.map.caption}</span></div></div>
 <section class="travel-board" aria-labelledby="travel-title"><div class="travel-title"><h2 id="travel-title">CHỌN ĐIỂM CÂU</h2><span>${player.maps.length}/3 đã mở</span></div><div class="travel-grid">${MAPS.map((m,i)=>{const owned=player.maps.includes(m.id);return `<button class="travel-card ${owned?'unlocked':'locked'} ${player.map===m.id?'selected':''}" data-travel="${m.id}" aria-label="${owned?'Ra câu tại':'Mở tại cửa hàng:'} ${m.name}"><div class="travel-art">${mapArt(m.id)}<span class="map-number">0${i+1}</span><span class="map-state">${icon(owned?'pin':'lock')}</span></div><div class="travel-info"><div><strong>${m.name}</strong><small>${owned?FISH.filter(f=>f.maps.includes(m.id)).length+' loài cá':money(m.price)+' xu để mở'}</small></div>${icon(owned?'arrow':'lock')}</div></button>`;}).join('')}</div></section></section>`;
}
export function floatSVG(){return `<svg viewBox="0 0 72 130" aria-hidden="true"><g id="zoom-float"><path d="M36 12v87" stroke="#263F37" stroke-width="3"/>${Array.from({length:8},(_,i)=>`<path d="M36 ${12+i*8}v8" stroke="${i%2?'#F2D876':'#B44727'}" stroke-width="5"/>`).join('')}<ellipse cx="36" cy="83" rx="7" ry="16" fill="#7A8561"/><path d="M36 99v19" stroke="#183D37" stroke-width="2"/></g><path d="M0 88h72v42H0Z" fill="#DCEAE1" opacity=".95"/><path d="M3 88q15-4 33 0t33 0" class="float-water"/></svg>`;}
export function renderRig(player,game){
 const lure=game.rod.tech==='lure';
 return `<section class="game-window">${heading('CHUẨN BỊ TRƯỚC KHI XUỐNG NƯỚC','Đồ nghề','Chọn cần, lắp mồi, cân phao. Chuẩn bị tốt, câu nhẹ tay.',`<a class="button primary" href="#fishing">Mang ra ao ${icon('arrow')}</a>`)}<div class="rig-layout">
 <section class="panel rig-form"><h2>Túi đồ của bạn</h2><div class="gear-slots">${RODS.map(r=>`<button data-equip="${r.id}" class="gear-slot ${r.id===player.rod?'equipped':''}" aria-label="${player.rods.includes(r.id)?'Trang bị':'Mua tại chợ:'} ${r.name}" aria-pressed="${r.id===player.rod}"><span>${toolArt('rod',r.id)}</span><small>${r.id===player.rod?'Đang lắp':player.rods.includes(r.id)?'Có sẵn':'Chưa có'}</small>${!player.rods.includes(r.id)?icon('lock'):''}</button>`).join('')}</div><label for="rod">Cần & kỹ thuật</label><select id="rod">${RODS.filter(r=>player.rods.includes(r.id)).map(r=>`<option value="${r.id}" ${r.id===player.rod?'selected':''}>${r.name} · ${r.label}</option>`).join('')}</select><p class="hint-note">${game.rod.note}</p><label for="bait">Mồi câu</label><select id="bait">${BAITS.filter(b=>lure?b.id==='lure':b.id!=='lure').map(b=>`<option value="${b.id}" ${b.id===player.bait?'selected':''}>${b.name} · ${b.id==='lure'?'dùng lại':(player.baits[b.id]||0)+' phần'}</option>`).join('')}</select><p class="hint-note" id="bait-note">${getBait(player.bait).note}</p><div class="free-bait"><span>${toolArt('bait','worm')}</span><div><h3>Giun nhà trồng</h3><p id="worm-count">${player.baits.worm}/60 phần trong túi</p><button id="dig" class="small">Đào giun +6</button></div></div></section>
 <section class="rig-drawing"><div class="gear-label">${icon('check')} ĐANG TRANG BỊ</div><h2>${game.rod.name}</h2><svg viewBox="0 0 310 360" aria-label="Minh họa bộ cần và phao"><path d="M27 300 217 27" stroke="#937344" stroke-width="7" stroke-linecap="round"/><path d="M217 27q16 8 18 38v233" stroke="#657a66" stroke-width="1.5" fill="none"/><path d="M235 105v74" stroke="#183D37" stroke-width="3"/>${Array.from({length:8},(_,i)=>`<path d="M235 ${106+i*6}v6" stroke="${i%2?'#F5CC5B':'#B44727'}" stroke-width="5"/>`).join('')}<ellipse cx="235" cy="177" rx="9" ry="22" fill="#7B8856"/><path d="M235 299q0 24-13 18q-6-2-4-8" stroke="#183D37" fill="none" stroke-width="2"/><path d="M219 313q-10-15-2-18" stroke="#9B7652" fill="none" stroke-width="4"/><path d="M137 224q58-8 130 0" stroke="#729B88" fill="none" stroke-width="2" stroke-dasharray="5 6"/>${lure?'<circle cx="62" cy="262" r="14" fill="#183D37"/><path d="M62 262h19" stroke="#183D37" stroke-width="3"/>':''}</svg><div class="gear-specs"><span>${game.rod.label}</span><span>Sức cần ${game.rod.power.toFixed(1)}</span></div><p>${lure?'Bộ lure có máy và mồi mềm. Ra ao, bật thu mồi để cá chú ý.':'Cần, dây, phao, chì và lưỡi. Bộ câu tay gọn nhẹ của bạn.'}</p></section>
 <section class="panel rig-summary"><p class="eyebrow">TINH CHỈNH</p><h2>Tầng mồi & phao</h2><div class="input-head"><label for="depth">Độ sâu mồi</label><output id="depth-out">${player.rig.depth.toFixed(1)} m</output></div><input id="depth" type="range" min="0.4" max="3.2" step="0.1" value="${player.rig.depth}" ${lure?'disabled':''}><p class="hint-note">Điểm hiện tại sâu ${game.spotData.depth.toFixed(1)} m. Đặt sát đáy để tìm cá ăn đáy.</p><div class="input-head"><label for="lead">Chì cân phao</label><output id="lead-out">${player.rig.lead.toFixed(2)} g</output></div><input id="lead" type="range" min="0.7" max="1.5" step="0.01" value="${player.rig.lead}" ${lure?'disabled':''}><div id="rig-state" class="rig-state ${rigError(player)?'error':''}">${lure?'Bộ lure: không dùng phao.':rigError(player)||`Phao nổi ${floatMarks(player)} vạch · Bộ câu sẵn sàng`}</div><button id="balance" class="green" ${lure?'disabled':''}>${icon('wave')} Cân về 4 vạch</button><div class="rig-tip">${icon('leaf')}<p>Cần tre luôn miễn phí.<br>Hết mồi thì đào giun, rồi lại ra ao.</p></div><p class="fineprint">Tải và độ sâu là tham số mô phỏng trong game.</p></section></div></section>`;
}
export function renderLearn(player){return `<section class="game-window">${heading('HỌC MỘT NHỊP · THÊM MỘT CƠ HỘI','Học câu','Ba bài nhập môn. Hoàn thành lần đầu, mỗi bài nhận 2.500 xu.',`<span class="pill">${icon('book')}${player.lessons.length}/3 hoàn thành</span>`)}<div class="split"><section class="lesson-list">${LESSONS.map((l,i)=>{const complete=player.lessons.includes(l.id);return `<article class="lesson-row ${complete?'complete':''}"><div class="lesson-number">${complete?icon('check'):'0'+(i+1)}</div><div class="lesson-content"><span class="lesson-tag">${complete?'ĐÃ HOÀN THÀNH':'BÀI '+(i+1)+' · NHẬP MÔN'}</span><h2>${l.name}</h2><p>${l.question}</p><span class="lesson-reward">${icon('coin')}${complete?'Đã nhận thưởng':'+2.500 xu'}</span></div><button data-lesson="${l.id}" class="${complete?'':'green'}">${complete?'Ôn lại':'Học ngay'} ${icon('arrow')}</button></article>`;}).join('')}<p class="fineprint">Các bài học giải thích cơ chế game; tình huống câu ngoài đời có thể khác.</p></section><aside class="learning-aside"><span class="lesson-emblem">${icon('rod')}</span><p class="eyebrow">BÍ KÍP TÂN THỦ</p><h2>Nhìn phao.<br>Giữ nhịp.<br>Nhẹ tay.</h2><ol class="tip-list"><li><span>01</span>Phao rung nhẹ? Chờ thêm.</li><li><span>02</span>Chìm rõ? Giật đúng lúc.</li><li><span>03</span>Cá bứt mạnh? Nới lực.</li></ol><a class="button primary" href="#fishing">Thử ngay ở ao ${icon('arrow')}</a></aside></div></section>`;}
export function journalRows(player,query=''){
 const rows=FISH.filter(f=>f.name.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
 return rows.length?rows.map(f=>{const c=player.collection[f.id];return `<article class="fish-row fish-card ${c?'discovered':'unknown'}"><div class="fish-card-top"><span>No. ${f.id.slice(-2)}</span><span>${icon(c?'check':'lock')}${c?'Đã khám phá':'Chưa khám phá'}</span></div><div class="fish-art">${fishArt(f)}</div><div class="fish-card-copy"><h2>${f.name}</h2><p>${c?`Đã gặp ${c.count} lần`:'Chờ bạn tìm thấy'}</p><div class="fish-record">${c?`${icon('trophy')} Kỷ lục <strong>${kg(c.best)} kg</strong>`:'<span>— —</span>'}</div><div class="fish-habitat">${icon('pin')}${f.maps.map(id=>getMap(id).name).join(' · ')}</div></div></article>`;}).join(''):'<p class="empty">Không có loài phù hợp. Thử tên ngắn hơn.</p>';
}
export function renderJournal(player){const known=Object.keys(player.collection).length;return `<section class="game-window">${heading('BỘ SƯU TẬP CỦA CẦN THỦ','Sổ cá','Mỗi loài cá là một lần khám phá. Thả về nước, thành tích vẫn ở đây.',`<button id="export">Xuất bản lưu ${icon('arrow')}</button>`)}<div class="journal-summary"><div class="collection-progress">${icon('collection')}<div><strong>${known}<small> / 12 loài</small></strong>${progressLine(known,12)}</div></div>${[['fish',player.catches,'Cá đã câu'],['wave',player.released,'Đã thả'],['coin',player.sold,'Đã bán']].map(([symbol,n,label])=>`<div class="journal-stat">${icon(symbol)}<div><strong>${n}</strong><small>${label}</small></div></div>`).join('')}</div><div class="filter"><label class="search-label" for="fish-search">Tìm trong bộ sưu tập</label><input id="fish-search" type="search" placeholder="Tên cá: chép, rô, lóc…" autocomplete="off"></div><div class="fish-list" id="fish-results">${journalRows(player)}</div><p class="fineprint">Hình cá là minh họa. Phân bố và tập tính là mô hình trong game.</p></section>`;}
function shopButton(player,kind,item,owned=false){return `<button data-buy="${kind}" data-id="${item.id}" ${owned||player.coins<item.price?'disabled':''} class="${owned?'':'green'}">${owned?`${icon('check')} Đã sở hữu`:player.coins<item.price?'Thiếu xu':'Mua '+money(item.price)}</button>`;}
export function renderShop(player){return `<section class="game-window">${heading('SẮM ĐỒ CHO BUỔI CÂU TIẾP THEO','Chợ bên bến','Bán cá, kiếm xu, nâng bộ đồ. Cần tre và giun miễn phí luôn có sẵn.',`<span class="pill gold">${icon('coin')}${money(player.coins)} xu</span>`)}<div class="shop-tabs" aria-label="Nhóm hàng">${[['all','Tất cả'],['rod','Cần câu'],['bait','Mồi'],['map','Bản đồ']].map(([id,label])=>`<button data-shop-category="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><div id="shop-inventory" class="shop-inventory" data-filter="all">
 <section class="shop-section" data-category="rod"><h2>${icon('rod')} Cần & kỹ thuật</h2><div class="product-grid">${RODS.map(r=>`<article class="product"><div class="product-top"><span>${r.label}</span><span>${player.rods.includes(r.id)?'SỞ HỮU':'NÂNG CẤP'}</span></div><div class="product-icon">${toolArt('rod',r.id)}</div><h3>${r.name}</h3><p>${r.note}</p><div class="product-spec">Sức cần <b>${r.power.toFixed(1)}</b><span class="price">${r.price?money(r.price)+' xu':'Miễn phí'}</span></div>${shopButton(player,'rod',r,player.rods.includes(r.id))}</article>`).join('')}</div></section>
 <section class="shop-section" data-category="bait"><h2>${icon('bag')} Mồi câu</h2><div class="product-grid">${BAITS.filter(b=>b.id!=='lure').map(b=>`<article class="product"><div class="product-top"><span>${b.amount} PHẦN / GÓI</span><span>CÓ ${player.baits[b.id]}</span></div><div class="product-icon">${toolArt('bait',b.id)}</div><h3>${b.name}</h3><p>${b.note}</p><div class="product-spec"><span class="price">${money(b.price)} xu</span></div>${shopButton(player,'bait',b)}</article>`).join('')}</div></section>
 <section class="shop-section" data-category="map"><h2>${icon('pin')} Những góc bờ mới</h2><div class="product-grid">${MAPS.map(m=>`<article class="product map-product"><div class="product-map-art">${mapArt(m.id)}</div><h3>${m.name}</h3><p>${m.caption}. ${FISH.filter(f=>f.maps.includes(m.id)).length} loài cá để khám phá.</p><div class="product-spec"><span class="price">${m.price?money(m.price)+' xu':'Bến khởi đầu miễn phí'}</span></div>${shopButton(player,'map',m,player.maps.includes(m.id))}</article>`).join('')}</div></section></div><div class="shop-free">${icon('leaf')}<p>Hết xu? Về bàn đồ đào giun miễn phí.</p><a class="button small" href="#rig">Về đồ nghề ${icon('arrow')}</a></div></section>`;}
export function renderFishing(player,game,warning){return `${warningHTML(warning)}<section class="fishing-layout"><div class="scene" data-map="${player.map}" data-phase="${game.phase}" data-assist="${player.settings.assist}"><img class="scene-bg" src="./assets/ao-lang.webp" alt=""><canvas id="water" role="img" aria-label="Ao câu, cần, dây và phao. Chọn điểm bằng các nút trong bảng đồ nghề và chơi bằng nút phía dưới."></canvas><div class="scene-vignette"></div>
 <div class="location-hud">${icon('pin')}<div><p class="eyebrow">BUỔI CÂU CỦA BẠN</p><h1 id="map-heading">${game.map.name}</h1><p id="map-description">${game.map.caption}</p></div></div><div class="scene-tools"><button class="icon-button" id="help" aria-label="Cách chơi">${icon('help')}</button><button class="icon-button" id="pause" aria-label="Tạm dừng buổi câu" aria-pressed="${game.paused}">${icon(game.paused?'play':'pause')}</button></div>
 <div class="map-strip" aria-label="Chọn vùng câu">${MAPS.map(m=>`<button data-map="${m.id}" aria-pressed="${m.id===player.map}" ${!player.maps.includes(m.id)?'disabled':''}>${!player.maps.includes(m.id)?icon('lock'):''}${m.name}</button>`).join('')}</div><div class="session-hud">${icon('clock')}<div><span id="timer-label">${player.settings.deadline?'Giờ về nhà':'Bên bờ nước'}</span><strong id="session-clock" class="num">00:00</strong></div></div><div class="float-zoom" id="float-zoom"><div class="float-zoom-title">PHAO CÂU</div>${floatSVG()}<span id="float-label">Cận cảnh phao</span></div><div class="scene-caption"><strong id="spot-name">${game.spotData.name}</strong><span id="spot-depth">Sâu ${game.spotData.depth.toFixed(1)} m</span><span id="tech-label">${game.rod.label}</span></div>
 <div class="scene-bottom"><div class="status-box"><span class="status-gem" aria-hidden="true"></span><div><span id="status-title">Sẵn sàng</span><span id="status-copy">${esc(game.message)}</span></div></div><div class="phase-track" aria-label="Các bước của lượt câu">${['Thả','Chờ','Giật','Dẫn','Lên bờ'].map((s,i)=>`<span data-phase-step="${i}"><i>${i+1}</i>${s}</span>`).join('')}</div><div class="water-controls"><button class="primary" id="cast">${icon('rod')}Thả câu <span class="key">Space</span></button><button class="green" id="strike" disabled>${icon('target')}Giật cần <span class="key">Space</span></button><button id="retrieve" disabled>${icon('arrow')}<span>Thu cần</span></button></div>
 <div class="fight" id="fight" hidden><div class="meter-head"><strong id="fight-title">GIỮ CÁ TRONG TAY!</strong><span id="tension-value" class="num">44% lực căng</span></div><div class="tension-track" role="meter" aria-label="Lực căng dây" aria-valuemin="0" aria-valuemax="100" aria-valuenow="44"><i class="tension-marker" id="tension-marker"></i></div><p id="fight-hint">Giữ trong vùng xanh. Nới khi cá bứt.</p><div class="meter-head"><span>Đưa cá lên bờ</span><span id="progress-value" class="num">0%</span></div><div class="energy-track" role="progressbar" aria-label="Tiến độ đưa cá lên bờ" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="progress-bar"></i></div><div class="fight-actions"><button class="green" id="pull" aria-pressed="false">Bật dẫn cá <span class="key">A</span></button><button id="ease">Nới lực <span class="key">D</span></button></div></div></div></div>
 <details class="bank-panel" ${matchMedia('(min-width: 1000px) and (min-height: 620px)').matches?'open':''}><summary>${icon('bag')}<span>ĐIỂM CÂU & ĐỒ NGHỀ</span>${icon('chevron')}</summary><div class="bank-inner"><div class="bank-spots"><h2>Chọn góc bờ</h2><div class="spot-list">${game.map.spots.map((s,i)=>`<button data-spot="${i}" aria-pressed="${i===game.spot}"><span>${icon('pin')}${s.name}</span><small>${s.depth.toFixed(1)} m</small></button>`).join('')}</div></div><div class="bank-equipment"><h2>Bộ đang lắp</h2><div class="equipment-slot"><span>${toolArt('rod',player.rod)}</span><div><strong id="bank-rod">${game.rod.name}</strong><small id="bank-bait">${getBait(player.bait).name}</small></div></div><div class="spec"><span>Mồi còn</span><strong id="bank-count" class="num">${player.bait==='lure'?'Dùng lại':(player.baits[player.bait]||0)+' phần'}</strong></div><div class="spec"><span>Tầng mồi</span><strong>${player.rig.depth.toFixed(1)} m</strong></div><a class="button small" href="#rig">Chỉnh bộ câu ${icon('arrow')}</a></div><div class="bank-guide"><label class="checkline"><input type="checkbox" id="assist" ${player.settings.assist?'checked':''}>Gợi ý đọc phao</label><p class="hint-note">Rung nhẹ: chờ. Chìm rõ: giật.<br>Cá bứt, lực đỏ: nới.</p><button id="new-session" class="small" hidden>Buổi câu mới</button></div></div></details></section>`;}
