import {inventoryFor,BAG_TYPES,spareAccessoryCount,validateDeparture} from './inventory.js';
import {floatState} from './rig-physics.js';
import {getRigStats,getEquipmentSpecs,RIG_OPTIONS,validateRig} from './equipment.js';
import {STARTER_STEPS} from './tutorial.js';
import {GATHER_SOURCES} from './bait-system.js';
import {containerUsage} from './catch-inventory.js';
import {snagChance} from './water-world.js';
import {MAPS,FISH,RODS,BAITS,BAGS,ACCESSORIES,ACCESSORY_SLOTS,TECHNIQUES,LESSONS,getMap,getRod,getBait,getBag,usesFloat,usesReel,acceptsBait,slotItem,loadoutStats} from './content.js';
import {floatMarks,rigError,FIGHT_ZONE} from './engine.js';
import {getContainer} from './catch-fate.js';
// Presentation only: the simulation, currency and save format remain in their existing modules.
const money=v=>new Intl.NumberFormat('vi-VN').format(v);
const kg=v=>new Intl.NumberFormat('vi-VN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

const paths={
 fish:'M4 12c5-7 12-7 17 0-5 7-12 7-17 0ZM4 12 1 8v8l3-4Zm11-2h.01M9 7l3-4 3 4M9 17l3 4 3-4',
 rod:'M4 21 17 3M17 3q4 4 3 9v5q0 5-4 3v-3M6 17l3 2',
 bag:'M5 7h14l2 14H3L5 7Zm3 0V5a4 4 0 0 1 8 0v2M8 12h8M9 16h6',
 book:'M12 5q-5-3-10 0v15q5-3 10 0 5-3 10 0V5q-5-3-10 0Zm0 0v15M5 9h4M15 9h4M5 13h4M15 13h4',
 collection:'M4 3h16v18H4V3Zm3 4h10M7 17h10M7 12q5-5 10 0-5 5-10 0Zm8-1h.01',
 shop:'M3 9h18l-2-6H5L3 9Zm0 0v2a3 3 0 0 0 6 0 3 3 0 0 0 6 0 3 3 0 0 0 6 0V9M5 14v7h14v-7M9 21v-6h6v6',
 coin:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 6v12M15 8h-5a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H9',
 settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Zm7 9a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
 pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 1 1 14 0Zm-4 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 lock:'M5 10h14v11H5V10Zm3 0V7a4 4 0 0 1 8 0v3M12 14v3',
 check:'m5 12 4 4L19 6', arrow:'M4 12h16m-6-6 6 6-6 6', back:'M20 12H4m6-6-6 6 6 6', play:'m8 4 13 8-13 8V4Z', pause:'M8 4v16M16 4v16',
 help:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM9 8a3 3 0 0 1 6 0c0 3-3 2-3 5M12 17h.01',
 clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 6v6l4 2',
 trophy:'M8 3h8v7a4 4 0 0 1-8 0V3Zm0 2H3v3a4 4 0 0 0 5 4m8-7h5v3a4 4 0 0 1-5 4M12 14v6M7 21h10',
 wave:'M2 8q3-4 6 0t6 0 6 0M2 14q3-4 6 0t6 0 6 0M2 20q3-4 6 0t6 0 6 0',
 target:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-5 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0ZM12 12h.01',
 chevron:'m6 9 6 6 6-6', leaf:'M20 3C9 2 2 8 5 16c8 5 16-2 15-13ZM5 20 16 9',
 home:'m3 10 9-7 9 7v11h-6v-7H9v7H3V10Z',
 sound:'M3 9h4l5-4v14l-5-4H3V9Zm13-1a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14',
 muted:'M3 9h4l5-4v14l-5-4H3V9Zm13 1 5 5m0-5-5 5',
 info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 11v6M12 7h.01',
};
export function icon(name,className=''){return `<svg class="icon ${className}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||''}"/></svg>`;}
export const NAV_ITEMS=[['prepare','rod','Đi câu'],['rig','bag','Đồ nghề'],['learn','book','Học câu'],['journal','collection','Sổ cá'],['shop','shop','Chợ bến']];
export function rankFor(catches){
 const ranks=[[0,'Tân thủ'],[5,'Cần thủ ao làng'],[15,'Tay câu vững'],[30,'Lão làng'],[60,'Đại lão câu cá']];
 const i=ranks.findLastIndex(([n])=>catches>=n),start=ranks[i][0],next=ranks[i+1]?.[0];
 return {name:ranks[i][1],count:catches-start,max:next?next-start:1,label:next?`${catches} / ${next} cá`:`${catches} cá · Bậc cao nhất`,complete:!next};
}
export function avatarArt(){return `<svg viewBox="0 0 64 64" aria-hidden="true"><circle cx="32" cy="32" r="30" fill="#284f40"/><path d="M14 62q0-19 18-19t18 19" fill="#a5956b"/><path d="M23 25h18v12q-2 13-9 13t-9-13" fill="#e8bd83"/><path d="M11 28 32 5l21 23q-22 9-42 0" fill="#e3bd71" stroke="#836335" stroke-width="2"/><path d="M21 27 32 8l11 19M11 28h42" fill="none" stroke="#b48b47" stroke-width="2"/><path d="M27 36h1m8 0h1M28 43q4 3 8 0" stroke="#674e31" stroke-width="2" stroke-linecap="round"/></svg>`;}
export function fishArt(f){
 const color=f?.color||'#71847c',shape=f?.shape||'carp',id=f?.id||'unknown';
 const [rx,ry]=({catfish:[69,18],long:[71,15],knife:[67,23],round:[48,29],grouper:[58,26],carp:[54,24]})[shape],head=98+rx-13;
 const body=shape==='knife'?'<path d="M29 40q33-47 111-15 21 9 24 19-22 36-113 16Z"/>':`<ellipse cx="98" cy="44" rx="${rx}" ry="${ry}"/>`;
 const pattern=f?.pattern==='stripes'?`<path d="M68 19l-4 45M84 16l-3 52M100 17l-2 53M116 19l-1 44" stroke="#fff" stroke-opacity=".3" stroke-width="4"/>`:f?.pattern==='spots'?Array.from({length:9},(_,i)=>`<circle cx="${53+(i%5)*19}" cy="${34+Math.floor(i/5)*16}" r="${id==='fish_24'?5:2.8}" fill="${id==='fish_24'?'#263d3b':'#d6a578'}" opacity=".65"/>`).join(''):`<path d="M63 31q10 15 0 26m16-29q10 16 0 31m16-31q10 16 0 31m16-29q10 14 0 26" stroke="#fff" stroke-opacity=".15" fill="none" stroke-width="1.5"/>`;
 const whiskers=shape==='catfish'?`<path d="M${head+8} 42q19-18 32-12M${head+8} 49q18 2 25 19" fill="none" stroke="${color}" stroke-width="2"/>`:'';
 const fin=shape==='round'?'<path d="M64 26 78 7l14 7 15-11 21 20M76 63l17 19 22-18"/>':'<path d="M68 28 93 10 122 26M82 61l21 16 17-19"/>';
 return `<svg viewBox="0 0 200 88" aria-hidden="true"><g fill="${color}"><path d="M${98-rx+8} 44 10 23 13 65Z"/>${fin}${body}</g>${pattern}<path d="M${98-rx+12} 50q48 18 ${rx*2-25} -3" fill="none" stroke="#fff" stroke-opacity=".25" stroke-width="3"/><path d="M${head-7} 30q-9 12 0 25" stroke="#183D37" fill="none" opacity=".35"/><circle cx="${head+1}" cy="36" r="3.5" fill="#fff9eb"/><circle cx="${head+2}" cy="36" r="1.8" fill="#183D37"/>${whiskers}</svg>`;
}
export function toolArt(kind,id=''){
 if(kind==='bag'){
  const bag=getBag(id);
  return `<svg viewBox="0 0 180 120" aria-hidden="true"><path d="M48 34q8-25 31-25t31 25" fill="none" stroke="#665b40" stroke-width="6"/><path d="m29 29 108 5 21 60-124 13Z" fill="${bag.color}" stroke="#5d6046" stroke-width="3"/><path d="m36 43 105 5m-95-9 5 60m71-54 10 51" fill="none" stroke="#e2d4b0" stroke-width="3"/><path d="m70 58 40 2 7 26-46 3Z" fill="#344f43" fill-opacity=".35" stroke="#5d6046" stroke-width="2"/><path d="m84 31 5 71" stroke="#665b40" stroke-width="5"/><rect x="80" y="67" width="15" height="12" rx="2" fill="#cfb575"/></svg>`;
 }
 if(kind==='rod'){
  const rod=getRod(id),colors={don:'#a68248',dai:'#466d54',lure:'#456d8a',bottom:'#735871',iso:'#688696'};
  return `<svg viewBox="0 0 200 130" aria-hidden="true"><path d="M28 111 150 19" stroke="${colors[rod.tech]}" stroke-width="6" stroke-linecap="round"/><path d="m38 104 16-12" stroke="#58482b" stroke-width="9" stroke-linecap="round"/><path d="m75 74 3 3m25-25 3 3m23-22 3 3" stroke="#dfc173" stroke-width="3"/><path d="M150 19q15 5 16 26v58q0 17-13 9v-8" fill="none" stroke="#81978c" stroke-width="1.5"/>${usesReel(rod)?'<circle cx="66" cy="94" r="12" fill="#c49b53" stroke="#34574a" stroke-width="4"/><path d="m56 87-8-12m26 26 11 5" stroke="#34574a" stroke-width="4"/>':''}${usesFloat(rod)?'<path d="M166 58v22" stroke="#d07240" stroke-width="4"/><path d="M166 64v5m0 5v4" stroke="#efd274" stroke-width="4"/>':''}</svg>`;
 }
 const svg=inner=>`<svg viewBox="0 0 140 110" aria-hidden="true">${inner}</svg>`;
 if(kind==='accessory'){
  const assetKey=ACCESSORIES.find(a=>a.id===id)?.assetKey;
  if(assetKey)return `<img class="fishing-line-icon" src="./assets/items/lines/${assetKey}/icon.webp" alt="" loading="lazy" decoding="async" width="256" height="256" data-line-image="${assetKey}" data-image-stage="icon">`;
  const slot=ACCESSORIES.find(a=>a.id===id)?.slot||id;
  const arts={
   line:'<ellipse cx="70" cy="55" rx="30" ry="34" fill="#acbfa5" stroke="#496c5a" stroke-width="6"/><ellipse cx="70" cy="55" rx="12" ry="18" fill="#eadfc6"/><path d="M92 76q37 15 17-37" fill="none" stroke="#496c5a" stroke-width="3"/><path d="M43 45q28 16 55 0m-55 12q28 16 55 0" fill="none" stroke="#e5eacc" stroke-width="2"/>',
   hook:'<path d="M73 18v51q0 31-25 21-14-6-7-22l10 7" fill="none" stroke="#647c78" stroke-width="7" stroke-linecap="round"/><ellipse cx="73" cy="17" rx="6" ry="9" fill="none" stroke="#647c78" stroke-width="4"/>',
   float:'<path d="M70 14v82" stroke="#446250" stroke-width="3"/><path d="M70 15v12m0 12v12" stroke="#b35d38" stroke-width="6"/><path d="M70 27v12m0 12v12" stroke="#e3bd67" stroke-width="6"/><ellipse cx="70" cy="74" rx="12" ry="20" fill="#95a36e"/><path d="M49 92q21-6 42 0" stroke="#79a393" stroke-width="2" fill="none"/>',
   reel:'<circle cx="68" cy="54" r="29" fill="#cca868" stroke="#47645b" stroke-width="6"/><circle cx="68" cy="54" r="15" fill="#91a48d" stroke="#47645b" stroke-width="4"/><path d="m90 75 16 14 11-3M49 34l-15-16m35 4V9" fill="none" stroke="#47645b" stroke-width="6" stroke-linecap="round"/>',
   net:'<path d="M62 70 30 101" stroke="#ae8852" stroke-width="9" stroke-linecap="round"/><ellipse cx="79" cy="46" rx="31" ry="35" transform="rotate(25 79 46)" fill="#87a799" fill-opacity=".35" stroke="#4e7462" stroke-width="5"/><path d="M53 30 88 78M63 18l36 48M85 17l22 30M57 62l43-33M51 46l37-29M70 77l40-37" fill="none" stroke="#79968b" stroke-width="2"/>'
  };
  return svg(arts[slot]||'');
 }
 if(id==='livefish')return fishArt({color:'#809b8d',shape:'long',pattern:'scales'});
 const baits={
  corn:'<path d="M46 88q-13-48 18-58 29-6 30 25T46 88" fill="#dfb753" stroke="#a38030" stroke-width="2"/><path d="m57 35 17 52M71 31l15 43M48 52l40-12M46 66l45-13M49 80l38-11" stroke="#f9dc87" stroke-width="3"/><path d="M42 65q-17 22 6 35l29-9" fill="#78924e"/>',
  dough:'<path d="M37 91 45 30h50l8 61Z" fill="#d2ad70" stroke="#a5844b" stroke-width="2"/><path d="M43 31q25 9 53 0" stroke="#87734c" fill="none" stroke-width="4"/><circle cx="70" cy="63" r="15" fill="#f2dfb6"/><path d="m58 65 8-9 8 9 7-6" fill="none" stroke="#758459" stroke-width="3"/>',
  shrimp:'<path d="M46 78q-20-41 12-49 37-10 37 26 0 20-26 29" stroke="#d89173" fill="none" stroke-width="16"/><path d="m63 32 12 8m-21 2 13 11m-13 7 12 9M82 31q16-18 27-14M91 40q22-7 28 2m-51 39-9 15 25-12" stroke="#ab7055" fill="none" stroke-width="3"/><circle cx="89" cy="42" r="3" fill="#3c4b3d"/>',
  cricket:'<ellipse cx="71" cy="56" rx="24" ry="13" fill="#7b9561"/><circle cx="47" cy="49" r="10" fill="#628254"/><path d="m64 64-20 20 20-1m20-19 14 20 16-1M69 53l21-23 23 17M44 41l-12-19m18 19 4-22" fill="none" stroke="#527347" stroke-width="3"/>',
  snail:'<path d="M32 86h72l8-21-13 10-7-16" fill="#91a377"/><circle cx="70" cy="55" r="28" fill="#c5a16e" stroke="#8f714d" stroke-width="3"/><path d="M70 31q31 10 15 32-14 20-29 0-10-14 9-18 15-1 8 11" fill="none" stroke="#8f714d" stroke-width="4"/>',
  leaf:'<path d="M67 95q-37-27-28-63 27 0 29 33 1-47 40-49 4 46-41 79" fill="#779960"/><path d="M67 95 94 31M67 95 47 45" stroke="#436d50" stroke-width="3"/>',
  pellet:'<g fill="#b99261" stroke="#8b6d4b" stroke-width="2"><ellipse cx="47" cy="65" rx="17" ry="12"/><ellipse cx="84" cy="70" rx="18" ry="12"/><ellipse cx="68" cy="46" rx="17" ry="12"/><ellipse cx="71" cy="89" rx="16" ry="10"/></g>',
  clam:'<path d="M70 87Q11 60 47 29q25-16 49 5 30 31-26 53" fill="#d5baa0" stroke="#a68b70" stroke-width="3"/><path d="M70 85 48 34m22 51-6-57m6 57 15-51m-15 51 27-31" stroke="#f3dbc1" stroke-width="4"/>',
  lure:'<path d="M28 58q41-48 73-10l17-12-2 40-14-15q-31 17-74-3" fill="#7b9871"/><path d="M54 69v14q0 10-10 2l-3-9" fill="none" stroke="#688078" stroke-width="3"/><circle cx="93" cy="49" r="4" fill="#efe2b5"/>',
  crank:'<path d="M27 52q40-31 79-4v18q-43 21-79-7Z" fill="#d3a85a" stroke="#8b7050" stroke-width="2"/><path d="m25 56-12 9m42 5v15q0 12-11 4m40-16v15q0 11-10 3" fill="none" stroke="#57766c" stroke-width="3"/><circle cx="94" cy="52" r="4" fill="#3c5a50"/>',
  spoon:'<ellipse cx="72" cy="49" rx="22" ry="35" transform="rotate(35 72 49)" fill="#adbfc0" stroke="#738e91" stroke-width="3"/><path d="m85 24-21 40" stroke="#eef1dc" stroke-width="4"/><path d="M52 76v18q0 14-12 3" fill="none" stroke="#5b7979" stroke-width="3"/>',
  popper:'<ellipse cx="70" cy="56" rx="31" ry="18" fill="#82a45e"/><path d="m46 49-17-16M46 65 27 82m52-14 21 21m-4-39 18-15" stroke="#56805a" stroke-width="5" fill="none"/><circle cx="89" cy="46" r="7" fill="#e9d77b"/><circle cx="90" cy="46" r="3" fill="#2c5346"/>'
 };
 baits.cloudbait=baits.dough.replace('#d2ad70','#b9c4a4');
 return svg(baits[id]||'<path d="M43 79q-26-40 9-40t15 29q-23 24 6 30 31 4 25-21" stroke="#b57d61" fill="none" stroke-width="13" stroke-linecap="round"/><path d="m41 56 10-4m-6-12 9 4m12 10 10 3M64 80l9 7m4 10 1-12" stroke="#e0ab81" stroke-width="3"/>');
}
export function mapArt(id,loading='lazy'){const m=getMap(id);return `<img src="${m.thumbnail}" alt="" loading="${loading}" decoding="async" width="320" height="180">`;}
export function renderMapAtlas(player){return `<p class="atlas-intro">${player.maps.length}/${MAPS.length} vùng đã mở · Mỗi vùng có 3 góc bờ. Mua vé mở một lần, quay lại tự do.</p><div class="atlas-grid">${MAPS.map((m,i)=>{const owned=player.maps.includes(m.id);return `<article class="atlas-card ${m.id===player.map?'selected':''}"><div class="atlas-art">${mapArt(m.id,'eager')}<span class="atlas-number">${String(i+1).padStart(2,'0')}</span><span class="water-tag">${m.water}</span></div><div class="atlas-copy"><h3>${m.name}</h3><p>${m.caption}</p><div class="atlas-spec"><span>${FISH.filter(f=>f.maps.includes(m.id)).length} loài</span><span>${TECHNIQUES[m.recommended].label}</span></div><button data-atlas-map="${m.id}" class="${owned?'green':''}">${icon(owned?'pin':'lock')}${owned?'Ra câu':'Mở '+money(m.price)+' xu'}</button></div></article>`;}).join('')}</div>`;}
function warningHTML(warning){return warning?`<div class="save-warning">${esc(warning)}</div>`:'';}
function heading(kicker,title,copy,action=''){return `<div class="page-head"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${copy}</p></div>${action}</div>`;}
function progressLine(value,total){return `<div class="quest-track"><i style="width:${Math.min(100,value/total*100)}%"></i></div>`;}
function bagSummary(player,game){
 const inv=inventoryFor(player),bag=BAG_TYPES[inv.bagId];
 return `<section class="bag-preparation" aria-labelledby="bag-heading"><div class="bag-art">${toolArt('bag',inv.bagId)}</div><div class="bag-copy"><p class="eyebrow">BAO ĐỰNG ĐỒ CÂU</p><h2 id="bag-heading">${bag.name}</h2><div class="bag-capacity"><span><b>${inv.carried.rods.length}/${bag.rods}</b> cần</span><span><b>${Object.values(inv.carried.baits).filter(n=>n>0).length}/${bag.baitTypes}</b> loại mồi</span><span><b>${spareAccessoryCount(inv,player)}/${bag.accessorySlots}</b> đồ dự phòng</span></div><p class="hint-note">Bộ đang lắp không chiếm ngăn dự phòng. ${game.atHome?'Soạn đồ trước khi ra bờ.':'Chỉ đổi đồ đã mang theo.'}</p></div><div class="bag-summary-actions"><a class="button" href="#rig">${icon('bag')} ${game.atHome?'Soạn túi':'Đồ mang theo'}</a></div></section>`;
}
export function renderFieldKit(player,game,filter='all'){
 const rod=game.rod,groups=[],inv=inventoryFor(player),bag=BAG_TYPES[inv.bagId];
 if(['all','rods'].includes(filter))groups.push(['Cần mang theo',RODS.filter(r=>inv.carried.rods.includes(r.id)).map(r=>({kind:'rod',item:r,active:r.id===player.rod,disabled:!['idle','failed','waiting'].includes(game.phase),copy:r.label}))]);
 if(['all','baits'].includes(filter))groups.push(['Mồi mang theo',BAITS.filter(b=>(inv.carried.baits[b.id]||0)>0).map(b=>({kind:'bait',item:b,active:b.id===player.bait,disabled:!acceptsBait(rod,b)||!(inv.carried.baits[b.id]>0),copy:!acceptsBait(rod,b)?'Không hợp cần đang dùng':b.reusable?'Dùng lại':(inv.carried.baits[b.id]||0)+' phần trong túi'}))]);
 if(['all','line'].includes(filter))groups.push([filter==='line'?'Thẻo nhỏ hơn đang mang':'Phụ kiện mang theo',ACCESSORIES.filter(a=>inv.carried.accessories.includes(a.id)&&(filter!=='line'||a.slot==='line'&&(a.diameter||.20)<game.stats.leaderDiameter)).map(a=>({kind:a.slot,item:a,active:player.equipment[a.slot]===a.id,disabled:a.slot==='float'?!usesFloat(rod):a.slot==='reel'?!usesReel(rod):false,copy:a.effect}))]);
 if(filter==='line')groups.unshift(['Cỡ thẻo của bộ câu',RIG_OPTIONS.leaders.filter(l=>l.diameterMm<(player.rig.leaderMm??.16)).map(l=>({kind:'leaderMm',item:{id:String(l.diameterMm),name:l.name},active:false,disabled:false,copy:`Tải thẻo ${l.strengthKg} kg · Cá thăm mồi nhanh hơn, sức chịu lực giảm.`}))]);
 return `<p class="hint-note">${bag.name} · Chỉ đổi sang đồ đã mang theo. Chọn đổi mồi hoặc thẻo sẽ thu cần; mồi còn nguyên được giữ trên lưỡi.</p>${groups.map(([label,items])=>`<section class="field-kit-group"><h3>${label}</h3>${items.length?`<div class="field-kit-list">${items.map(({kind,item,active,disabled,copy})=>`<button data-field-kind="${kind}" data-field-id="${item.id}" ${active||disabled?'disabled':''}><span><strong>${item.name}</strong><small>${copy}</small></span><em>${active?'Đang dùng':disabled?'Chưa dùng được':'Đổi sang'}</em></button>`).join('')}</div>`:'<p class="hint-note">Chưa mang theo thẻo nhỏ hơn. Soạn lại túi hoặc mua bộ thẻo mảnh tại Chợ bến cho buổi câu tiếp theo.</p>'}</section>`).join('')}`;
}
export function renderHome(player,game,warning){
 const featured=MAPS.slice(0,3).some(m=>m.id===player.map)?MAPS.slice(0,3):[game.map,...MAPS.filter(m=>m.id!==player.map)].slice(0,3);
 const known=Object.keys(player.collection).length,quests=[['Câu con cá đầu tiên',Math.min(player.catches,1),1,'prepare'],['Hoàn thành bài đọc phao',player.lessons.includes('signal')?1:0,1,'learn'],['Khám phá 3 loài cá',Math.min(known,3),3,'journal']];
 return `${warningHTML(warning)}<section class="camp-scene"><img class="camp-bg" src="${game.map.background}" alt="Cảnh ${game.map.name}: ${game.map.caption}"><div class="camp-shade"></div>
 <div class="camp-title"><p class="eyebrow"><span class="little-line"></span> GAME CÂU CÁ VIỆT NAM</p><h1>TRỐN VỢ<br><span>ĐI CÂU!</span></h1><p>${getRod(player.rod).name} sẵn rồi.<br>Ra ${game.map.name.toLocaleLowerCase('vi')} làm một buổi thôi!</p><div class="camp-actions"><a class="button primary start-button" href="#prepare">${icon('play')}<span>${player.casts?'TIẾP TỤC BUỔI CÂU':'XÁCH CẦN ĐI CÂU'}</span></a><button class="icon-button" id="home-help" aria-label="Cách chơi">${icon('help')}</button></div><button class="camp-keepnet" data-open-keepnet>${icon('fish')} Thành quả ở nhà · ${(player.homeFish||[]).length} con</button><button class="mode-button" id="home-mode">${icon('clock')}<span>${player.settings.deadline?`Trốn vợ · ${player.settings.deadline/60} phút`:'Thư thả · Không giới hạn'}</span>${icon('chevron')}</button></div>
 <aside class="quest-board"><div class="board-heading">${icon('target')}<h2>Hành trình cần thủ</h2></div><p class="board-subtitle">Mỗi buổi câu, tiến thêm một chút.</p>${quests.map(([name,value,total,target])=>`<a class="quest ${value===total?'complete':''}" href="#${target}"><span class="quest-mark">${icon(value===total?'check':'target')}</span><span class="quest-copy"><strong>${name}</strong><span class="quest-detail">${value===total?'Đã hoàn thành':`${value} / ${total}`}</span>${progressLine(value,total)}</span></a>`).join('')}<div class="board-footer">${icon('fish')}<span><b>${player.catches}</b> cá đã câu</span><span><b>${known}/${FISH.length}</b> loài</span></div></aside>
 <div class="camp-location">${icon('pin')}<div><strong>${game.map.name}</strong><span>${game.map.caption}</span></div></div>
 <section class="travel-board" aria-labelledby="travel-title"><div class="travel-title"><h2 id="travel-title">CHỌN ĐIỂM CÂU</h2><button class="atlas-open small" data-open-maps>${player.maps.length}/${MAPS.length} đã mở · Xem bản đồ ${icon('arrow')}</button></div><div class="travel-grid">${featured.map((m,i)=>{const owned=player.maps.includes(m.id);return `<button class="travel-card ${owned?'unlocked':'locked'} ${player.map===m.id?'selected':''}" data-travel="${m.id}" aria-label="${owned?'Ra câu tại':'Mở tại cửa hàng:'} ${m.name}"><div class="travel-art">${mapArt(m.id)}<span class="map-number">0${i+1}</span><span class="map-state">${icon(owned?'pin':'lock')}</span></div><div class="travel-info"><div><strong>${m.name}</strong><small>${owned?FISH.filter(f=>f.maps.includes(m.id)).length+' loài cá':money(m.price)+' xu để mở'}</small></div>${icon(owned?'arrow':'lock')}</div></button>`;}).join('')}</div></section></section>`;
}
export function floatSVG(){return `<svg viewBox="0 0 72 130" aria-hidden="true"><g id="zoom-float"><path d="M36 12v87" stroke="#263F37" stroke-width="3"/>${Array.from({length:8},(_,i)=>`<path d="M36 ${12+i*8}v8" stroke="${i%2?'#F2D876':'#B44727'}" stroke-width="5"/>`).join('')}<ellipse cx="36" cy="83" rx="7" ry="16" fill="#7A8561"/><path d="M36 99v19" stroke="#183D37" stroke-width="2"/></g><path d="M0 88h72v42H0Z" fill="#DCEAE1" opacity=".95"/><path d="M3 88q15-4 33 0t33 0" class="float-water"/></svg>`;}
export function renderInventoryOverview(player,{atHome=true}={}){
 const inv=inventoryFor(player);if(!inv)return '';
 const bag=BAG_TYPES[inv.bagId],carried=inv.carried,stored=inv.stored,disabled=atHome?'':'disabled';
 const total=obj=>Object.values(obj).reduce((n,v)=>n+v,0);
 const gearRow=(id,kind,from)=>{
   const active=kind==='rods'?id===player.rod:Object.values(player.equipment).includes(id);
   const item=kind==='rods'?getRod(id):ACCESSORIES.find(a=>a.id===id),to=from==='carried'?'stored':'carried';
   return `<li class="storage-row"><div><strong>${esc(item.name)}</strong><small>${from==='carried'?'Trong túi':'Kho nhà'}${active?' · Đang lắp':''}</small></div><button class="small" data-transfer-kind="${kind}" data-transfer-id="${id}" data-transfer-to="${to}" ${disabled||active&&from==='carried'?'disabled':''}>${from==='carried'?'Cất vào kho':kind==='rods'&&carried.rods.length>=bag.rods?'Đổi cần đang mang':'Bỏ vào túi'}</button></li>`;
 };
 return `<section class="panel inventory-panel" aria-label="Túi đồ và kho tại nhà"><div class="inventory-heading"><div><p class="eyebrow">CHUẨN BỊ HÀNH TRANG</p><h2>Túi đồ · Kho tại nhà</h2></div><a class="button small" href="#shop">Đổi túi ${icon('arrow')}</a></div>
 <label for="bag-select">Túi mang theo</label><select id="bag-select" ${disabled}>${Object.values(BAG_TYPES).filter(b=>(player.systems?.bags||['cloth']).includes(b.id)).map(b=>`<option value="${b.id}" ${b.id===inv.bagId?'selected':''}>${b.name} · ${b.rods} cần / ${b.baitTypes} mồi / ${b.accessorySlots} đồ dự phòng</option>`).join('')}</select>
 <div class="loadout-summary"><div><span>Cần trong túi</span><strong>${carried.rods.length}/${bag.rods}</strong></div><div><span>Loại mồi</span><strong>${Object.values(carried.baits).filter(n=>n>0).length}/${bag.baitTypes}</strong></div><div><span>Đồ dự phòng</span><strong>${spareAccessoryCount(inv,player)}/${bag.accessorySlots}</strong></div></div>
 <p class="hint-note">${atHome?'Bộ đang lắp không chiếm ngăn đồ dự phòng. Đồ mua mới được cất tại nhà.':'Bạn đang ở bờ: chỉ dùng đồ đã mang. Về nhà để chuyển đồ giữa túi và kho.'}</p>
 <details class="storage-group" open><summary>Cần câu · ${carried.rods.length} mang / ${stored.rods.length} cất</summary><ul class="storage-list">${carried.rods.map(id=>gearRow(id,'rods','carried')).join('')}${stored.rods.map(id=>gearRow(id,'rods','stored')).join('')}</ul></details>
 <details class="storage-group"><summary>Mồi câu · ${total(carried.baits)} mang / ${total(stored.baits)} cất</summary><ul class="storage-list">${BAITS.filter(b=>player.baits[b.id]>0).map(b=>{const carry=carried.baits[b.id]||0,store=stored.baits[b.id]||0;return `<li class="storage-row bait-storage"><div><strong>${esc(b.name)}</strong><small>Túi ${carry} · Kho ${store}${b.reusable?' · Dùng lại':''}</small></div><div class="bait-transfer-controls"><input type="number" min="1" max="${player.baits[b.id]}" value="${Math.min(6,player.baits[b.id])}" data-transfer-count="${b.id}" aria-label="Số phần ${esc(b.name)} muốn chuyển" ${disabled}><button class="small" data-transfer-bait="${b.id}" data-transfer-to="carried" ${disabled||!store?'disabled':''}>Bỏ vào túi</button><button class="small" data-transfer-bait="${b.id}" data-transfer-to="stored" ${disabled||!carry?'disabled':''}>Cất về kho</button></div></li>`;}).join('')}</ul></details>
 <details class="storage-group"><summary>Phụ kiện · ${carried.accessories.length} mang / ${stored.accessories.length} cất</summary><ul class="storage-list">${carried.accessories.map(id=>gearRow(id,'accessories','carried')).join('')}${stored.accessories.map(id=>gearRow(id,'accessories','stored')).join('')}</ul></details></section>`;
}
export function renderRigCalibration(player,game){
 const state=floatState(player,{bottomDepth:game.spotData.depth,current:game.map.current}),stats=getRigStats(player),float=usesFloat(game.rod),bottom=state.contact!=='suspended',hookY=float?Math.min(192,76+state.hookDepth/game.spotData.depth*116):190;
 const warnings=validateRig(player).warnings;
 const text=float?`${state.marks.toFixed(1)} vạch · Độ nhạy ${Math.round(state.sensitivity*100)}%`:'Không dùng phao · Theo dõi đầu cần và dây';
 return `<section class="calibration-lab" aria-label="Mô phỏng bộ câu"><div class="rig-chain">${['Cần','Dây trục','Thẻo',...(float?['Phao','Chì']:['Chì / mồi giả']),'Lưỡi','Mồi'].map(x=>`<span>${x}</span>`).join('')}</div><svg class="rig-tank" viewBox="0 0 320 232" role="img" aria-label="${esc(text)}. ${bottom?'Mồi chạm đáy':'Mồi lơ lửng'}"><path d="M12 72h296v136H12Z" fill="#dceae1"/><path d="M12 72q24-4 48 0t48 0t48 0t48 0t48 0t48 0" fill="none" stroke="#527e78"/><path d="M12 209h296" stroke="#ad9d78" stroke-width="7"/>${float?`<path d="M126 18v${hookY-18}" stroke="#748570" stroke-width="1.5"/><g transform="translate(126 ${72-state.marks*3.2})"><path d="M0 0v28" stroke="#b44727" stroke-width="4"/><path d="M0 7v4m0 7v4" stroke="#f2d876" stroke-width="4"/><ellipse cy="37" rx="7" ry="12" fill="#78845c"/></g>`:`<path d="M48 20 126 ${hookY}" stroke="#748570" stroke-width="1.5"/>`}<ellipse cx="126" cy="${Math.max(116,hookY-stats.sinkerDistance/game.spotData.depth*116)}" rx="5" ry="7" fill="#667077"/><path d="M126 ${hookY-9}v12q8 10 13 0" fill="none" stroke="#344f41" stroke-width="2"/><ellipse cx="137" cy="${hookY+3}" rx="5" ry="4" fill="#a95942"/><text x="170" y="35" fill="#365548" font-size="12">${float?'Phao '+state.marks.toFixed(1)+' vạch':'Bộ không dùng phao'}</text><text x="170" y="108" fill="#365548" font-size="12">Chì ${player.rig.lead.toFixed(2)} g</text><text x="170" y="154" fill="#365548" font-size="12">Tầng mồi ${state.hookDepth.toFixed(2)} m</text><text x="170" y="184" fill="#365548" font-size="12">${bottom?'Mồi chạm đáy':'Mồi lơ lửng'}</text></svg><div class="calibration-readout"><strong>${text}</strong><p>${esc(state.warning||'Bộ câu cân bằng. Theo dõi chuyển động rõ trước khi đóng cá.')}</p>${warnings.length?`<p class="rig-warning">${warnings.map(esc).join(' ')}</p>`:''}<small>Dây ${stats.mainlineMm===null?'PE #'+stats.peSize.toFixed(1):stats.mainlineMm.toFixed(2)+' mm'} · Thẻo ${stats.leaderMm.toFixed(2)} mm · Lưỡi #${stats.hookSize}</small></div></section>`;
}
export function renderRigPresets(player,game){return `<section class="panel preset-panel"><h2>Bộ câu đã lưu</h2><div class="preset-create"><label class="sr-only" for="preset-name">Tên bộ câu</label><input id="preset-name" maxlength="40" placeholder="Ví dụ: Rô sát bèo"><button id="save-rig" class="small" ${game.busy?'disabled':''}>Lưu bộ hiện tại</button></div><ul class="storage-list">${(player.systems?.rigPresets||[]).map(p=>`<li class="storage-row"><div><strong>${esc(p.name)}</strong><small>${esc(getRod(p.rod).label)} · ${esc(getBait(p.bait).name)}</small></div><div><button class="small" data-load-rig="${esc(p.id)}" ${!game.atHome||game.busy?'disabled':''}>Lắp bộ này</button><button class="small" data-remove-rig="${esc(p.id)}" ${!game.atHome||game.busy?'disabled':''}>Xóa</button></div></li>`).join('')}</ul></section>`;}
export function renderTutorial(player){
 const done=STARTER_STEPS.filter(s=>player.systems?.tutorial?.[s.id]?.completed).length;
 return `<section class="panel tutorial-panel" aria-label="Bài thực hành tân thủ"><div class="inventory-heading"><div><p class="eyebrow">HỌC QUA HÀNH ĐỘNG</p><h2>10 bài thực hành · ${done}/10</h2></div><a class="button small" href="#prepare">Ra bờ thực hành ${icon('arrow')}</a></div><p class="hint-note">Có thể câu ngay. Mỗi bài ghi nhận kết quả thực tế và giữ tiến trình sau khi tải lại.</p><ol class="tutorial-list">${STARTER_STEPS.map((step,i)=>{const state=player.systems?.tutorial?.[step.id];return `<li class="tutorial-step ${state?.completed?'complete':''}"><span class="lesson-number">${state?.completed?icon('check'):i+1}</span><div><strong>${esc(step.title)}</strong><p>${esc(step.hint)}</p></div><button class="small" data-tutorial-claim="${step.id}" ${!state?.completed||state.claimed?'disabled':''}>${state?.claimed?'Đã nhận':state?.completed?'Nhận '+step.reward+' xu':'Chưa đạt'}</button></li>`;}).join('')}</ol></section>`;
}
export function renderRig(player,game){
 const lure=game.rod.tech==='lure',float=usesFloat(game.rod),stats=game.stats,error=rigError(player);
 const leader=player.rig.leaderMm??.16,hookSize=player.rig.hookSize??4;
 const leaders=RIG_OPTIONS.leaders.some(o=>o.diameterMm===leader)?RIG_OPTIONS.leaders:[...RIG_OPTIONS.leaders,{diameterMm:leader}];
 const hooks=RIG_OPTIONS.hooks.some(o=>o.size===hookSize)?RIG_OPTIONS.hooks:[...RIG_OPTIONS.hooks,{size:hookSize}];
 return `<section class="game-window">${heading('CHUẨN BỊ TRƯỚC KHI XUỐNG NƯỚC','Đồ nghề','Chọn kỹ thuật, lắp mồi và phụ kiện cho chuyến câu của bạn.',`<a class="button primary" href="#prepare">Mang ra bờ ${icon('arrow')}</a>`)}${player.systems?.flags?.inventory===false?'':renderInventoryOverview(player,{atHome:game.atHome})}<div class="rig-layout">
 <section class="panel rig-form"><h2>Túi cần của bạn</h2><div class="gear-slots">${RODS.map(r=>`<button data-equip="${r.id}" class="gear-slot ${r.id===player.rod?'equipped':''}" aria-label="${player.rods.includes(r.id)?'Trang bị':'Mua tại chợ:'} ${r.name}" aria-pressed="${r.id===player.rod}"><span>${toolArt('rod',r.id)}</span><small>${r.name}</small><em>${r.id===player.rod?'Đang lắp':player.rods.includes(r.id)?'Có sẵn':'Chưa có'}</em>${!player.rods.includes(r.id)?icon('lock'):''}</button>`).join('')}</div><label for="rod">Cần & kỹ thuật</label><select id="rod">${RODS.filter(r=>player.rods.includes(r.id)).map(r=>`<option value="${r.id}" ${r.id===player.rod?'selected':''}>${r.name} · ${r.label}</option>`).join('')}</select><p class="hint-note">${game.rod.note}</p><label for="bait">Mồi câu</label><select id="bait">${BAITS.filter(b=>acceptsBait(game.rod,b)).map(b=>`<option value="${b.id}" ${b.id===player.bait?'selected':''} ${b.reusable&&!player.baits[b.id]?'disabled':''}>${b.name} · ${b.reusable?(player.baits[b.id]?'dùng lại':'chưa có'):(player.baits[b.id]||0)+' phần'}</option>`).join('')}</select><p class="hint-note" id="bait-note">${getBait(player.bait).note}</p><button class="small" data-stock="bait">Mua mồi ${icon('arrow')}</button><div class="free-bait"><span>${toolArt('bait','worm')}</span><div><h3>Giun nhà trồng</h3><p id="worm-count">${player.baits.worm} phần đang sở hữu</p><button id="dig" class="small">Đào giun +6</button><div class="gather-actions">${Object.values(GATHER_SOURCES).filter(x=>x.id!=='soil').map(x=>`<button class="small" data-gather="${x.id}" ${!game.atHome?'disabled':''}>${esc(x.name)} +${x.yieldCount}</button>`).join('')}</div></div></div></section>
 <section class="rig-drawing"><div class="gear-label">${icon('check')} ĐANG TRANG BỊ</div><h2>${game.rod.name}</h2><div class="equipped-rod-art">${toolArt('rod',player.rod)}</div><div class="gear-specs"><span>${game.rod.label}</span><span>Sức tải ${stats.power.toFixed(1)}</span></div><p>${lure?'Bật thu mồi để cá chú ý. Mồi giả sở hữu một lần, dùng lại mọi lượt.':float?'Quan sát phao. Dây khỏe và lưỡi tốt giúp bạn giữ cá lâu hơn.':'Đặt mồi đúng tầng. Đầu cần cong rõ và dây căng là tín hiệu giật.'}</p><div class="loadout-summary"><div><span>Nhịp giật</span><strong>${stats.biteWindow.toFixed(1)} giây</strong></div><div><span>Vợt hỗ trợ</span><strong>Sức cá ≤ ${stats.landAt}%</strong></div><div><span>Máy câu</span><strong>${usesReel(game.rod)?'Đang dùng':'Cần tay'}</strong></div></div></section>
 <section class="panel rig-summary"><p class="eyebrow">TINH CHỈNH</p><h2>${float?'Tầng mồi & phao':lure?'Thu mồi & kỹ thuật':'Tầng mồi & đầu cần'}</h2><div class="input-head"><label for="depth">Độ sâu mồi</label><output id="depth-out">${player.rig.depth.toFixed(1)} m</output></div><input id="depth" type="range" min="0.4" max="${game.map.maxDepth}" step="0.1" value="${player.rig.depth}" ${lure?'disabled':''}><p class="hint-note">${game.map.name} · ${game.spotData.name} sâu ${game.spotData.depth.toFixed(1)} m. Cá giữa nước thường ở khoảng nửa độ sâu, cá đáy ở sát đáy.</p><div class="input-head"><label for="lead">Chì cân phao</label><output id="lead-out">${player.rig.lead.toFixed(2)} g</output></div><input id="lead" type="range" min="0.4" max="3.5" step="0.01" value="${player.rig.lead}" ${!float?'disabled':''}><div id="rig-state" class="rig-state ${error?'error':''}">${error||(float?`Phao ${game.float.marks.toFixed(1)} vạch · ${game.float.warning||'Bộ câu sẵn sàng'}`:lure?'Không dùng phao. Bật thu mồi khi ra câu.':'Không dùng phao. Đọc tín hiệu đầu cần và dây.')}</div><button id="balance" class="green" ${!float?'disabled':''}>${icon('wave')} Cân về 4 vạch</button>${renderRigCalibration(player,game)}<div class="rig-tip">${icon('leaf')}<p>Đồ cất trong kho chỉ dùng được sau khi bỏ vào túi.<br>Máy và phao chỉ có tác dụng với cần phù hợp.</p></div><div class="rig-details-controls"><label for="leader-mm">Đường kính thẻo</label><select id="leader-mm">${leaders.map(o=>`<option value="${o.diameterMm}" ${o.diameterMm===(player.rig.leaderMm??.16)?'selected':''}>${o.diameterMm.toFixed(2)} mm</option>`).join('')}</select><label for="hook-size">Cỡ lưỡi</label><select id="hook-size">${hooks.map(o=>`<option value="${o.size}" ${o.size===(player.rig.hookSize??4)?'selected':''}>#${o.size}</option>`).join('')}</select><label for="leader-length">Chiều dài thẻo (m)</label><input id="leader-length" type="number" min="0.10" max="1.5" step="0.05" value="${player.rig.leaderLength??.25}"><label for="sinker-distance">Chì cách lưỡi (m)</label><input id="sinker-distance" type="number" min="0.05" max="1.5" step="0.01" value="${player.rig.sinkerDistance??.25}"></div><p class="fineprint">Tải và độ sâu là tham số mô phỏng trong game.</p></section></div>
 <section class="panel accessories-panel"><div class="accessories-head"><div><p class="eyebrow">NÂNG CẤP BỘ CÂU</p><h2>Phụ kiện đang lắp</h2></div><button data-stock="accessory" class="small">Mua phụ kiện ${icon('arrow')}</button></div><div class="accessory-slots">${Object.entries(ACCESSORY_SLOTS).map(([slot,label])=>{const item=slotItem(player,slot),active=slot==='reel'?usesReel(game.rod):slot==='float'?float:true;return `<div class="accessory-slot ${active?'':'inactive'}"><div class="accessory-art">${toolArt('accessory',item.id)}</div><label for="gear-${slot}">${label}</label><select id="gear-${slot}" data-accessory="${slot}" ${active?'':'disabled'}>${ACCESSORIES.filter(a=>a.slot===slot&&player.accessories.includes(a.id)).map(a=>`<option value="${a.id}" ${a.id===item.id?'selected':''}>${a.name}</option>`).join('')}</select><p>${active?item.effect:'Đang cất · '+(slot==='reel'?'Cần tay không dùng máy.':'Bộ cần này không dùng phao.')}</p></div>`;}).join('')}</div></section>${renderRigPresets(player,game)}</section>`;
}
export function renderLearn(player){return `${player.systems?.flags?.tutorial===false?'':renderTutorial(player)}<section class="game-window">${heading('HỌC MỘT NHỊP · THÊM MỘT CƠ HỘI','Học câu','Ba bài nhập môn. Hoàn thành lần đầu, mỗi bài nhận 2.500 xu.',`<span class="pill">${icon('book')}${player.lessons.length}/3 hoàn thành</span>`)}<div class="split"><section class="lesson-list">${LESSONS.map((l,i)=>{const complete=player.lessons.includes(l.id);return `<article class="lesson-row ${complete?'complete':''}"><div class="lesson-number">${complete?icon('check'):'0'+(i+1)}</div><div class="lesson-content"><span class="lesson-tag">${complete?'ĐÃ HOÀN THÀNH':'BÀI '+(i+1)+' · NHẬP MÔN'}</span><h2>${l.name}</h2><p>${l.question}</p><span class="lesson-reward">${icon('coin')}${complete?'Đã nhận thưởng':'+2.500 xu'}</span></div><button data-lesson="${l.id}" class="${complete?'':'green'}">${complete?'Ôn lại':'Học ngay'} ${icon('arrow')}</button></article>`;}).join('')}<p class="fineprint">Các bài học giải thích cơ chế game; tình huống câu ngoài đời có thể khác.</p></section><aside class="learning-aside"><span class="lesson-emblem">${icon('rod')}</span><p class="eyebrow">BÍ KÍP TÂN THỦ</p><h2>Nhìn phao.<br>Giữ nhịp.<br>Nhẹ tay.</h2><ol class="tip-list"><li><span>01</span>Phao rung nhẹ? Chờ thêm.</li><li><span>02</span>Chìm rõ? Giật đúng lúc.</li><li><span>03</span>Cá bứt mạnh? Nới lực.</li></ol><a class="button primary" href="#prepare">Thử ngay ở ao ${icon('arrow')}</a></aside></div></section>`;}
export function journalRows(player,query='',map='all'){
 const rows=FISH.filter(f=>f.name.toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))&&(map==='all'||f.maps.includes(map)));
 return rows.length?rows.map(f=>{const c=player.collection[f.id];return `<article class="fish-row fish-card ${c?'discovered':'unknown'}"><div class="fish-card-top"><span>No. ${f.id.slice(-2)}</span><span>${icon(c?'check':'lock')}${c?'Đã khám phá':'Chưa khám phá'}</span></div><div class="fish-art">${fishArt(f)}</div><div class="fish-card-copy"><h2>${f.name}</h2><p>${c?`Đã gặp ${c.count} lần`:'Chờ bạn tìm thấy'}</p><div class="fish-record">${c?`${icon('trophy')} Kỷ lục <strong>${kg(c.best)} kg</strong>`:'<span>— —</span>'}</div><div class="fish-habitat">${icon('pin')}${f.maps.map(id=>getMap(id).name).join(' · ')}</div><p class="fish-tips"><b>${f.depth==='bottom'?'Ăn đáy':f.depth==='surface'?'Mặt nước':f.depth==='cover'?'Ven chỗ trú':'Giữa nước'}</b> · ${f.tech.map(t=>TECHNIQUES[t].label).join(' / ')}<br>Mồi: ${f.baits.map(id=>getBait(id).name.toLocaleLowerCase('vi')).join(', ')}</p></div></article>`;}).join(''):'<p class="empty">Không có loài phù hợp. Thử tên ngắn hơn.</p>';
}
export function renderJournal(player){const known=Object.keys(player.collection).length;return `<section class="game-window">${heading('BỘ SƯU TẬP CỦA CẦN THỦ','Sổ cá','Mỗi loài cá là một lần khám phá. Thả về nước, thành tích vẫn ở đây.',`<button id="export">Xuất bản lưu ${icon('arrow')}</button>`)}<button class="journal-keepnet" data-open-keepnet>${icon('fish')} Xem cá · ${player.keptFish.length} trong rọ / ${(player.homeFish||[]).length} ở nhà</button><div class="journal-summary"><div class="collection-progress">${icon('collection')}<div><strong>${known}<small> / ${FISH.length} loài</small></strong>${progressLine(known,FISH.length)}</div></div>${[['fish',player.catches,'Cá đã câu'],['wave',player.released,'Đã thả'],['home',player.gifted,'Mang về nhà'],['coin',player.sold,'Đã bán']].map(([symbol,n,label])=>`<div class="journal-stat">${icon(symbol)}<div><strong>${n}</strong><small>${label}</small></div></div>`).join('')}</div><div class="filter"><label class="search-label" for="fish-search">Tìm trong bộ sưu tập</label><input id="fish-search" type="search" placeholder="Tên cá: chép, rô, lóc…" autocomplete="off"><label for="fish-map">Theo vùng câu</label><select id="fish-map"><option value="all">Tất cả ${MAPS.length} vùng</option>${MAPS.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></div><div class="fish-list" id="fish-results">${journalRows(player)}</div><p class="fineprint">Hình cá là minh họa. Phân bố và tập tính là mô hình trong game.</p></section>`;}
function shopStats(player,kind,item){
 const current=kind==='rod'?getRod(player.rod):kind==='bait'?getBait(player.bait):kind==='bag'?BAG_TYPES[inventoryFor(player).bagId]:slotItem(player,item.slot);
 const specs=entry=>kind==='bag'?['rods','baitTypes','accessorySlots'].map((key,i)=>({key,label:['Số cần','Loại mồi','Đồ dự phòng'][i],value:entry[key],digits:0,unit:''})):getEquipmentSpecs(kind,entry.id);
 const currentSpecs=specs(current),same=item.id===current.id;
 const value=row=>new Intl.NumberFormat('vi-VN',{minimumFractionDigits:row.digits,maximumFractionDigits:row.digits}).format(row.value)+(row.unit?' '+row.unit:'');
 return `<div class="product-comparison" data-compare="${esc(item.id)}"><small>${same?'Đang dùng':`So với ${esc(current.name)}`}</small><dl>${specs(item).map(row=>{const previous=currentSpecs.find(x=>x.key===row.key);return `<div><dt>${row.label}</dt><dd>${!same&&previous?`<span>${value(previous)}</span> → `:''}<b>${value(row)}</b></dd></div>`;}).join('')}</dl></div>`;
}
function shopButton(player,kind,item,owned=false){const away=player.systems?.trip?.active;return `<button data-buy="${kind}" data-id="${item.id}" ${owned||away||player.coins<item.price?'disabled':''} class="${owned?'':'green'}">${owned?`${icon('check')} Đã sở hữu`:away?'Về nhà để mua':player.coins<item.price?'Thiếu xu':'Mua '+money(item.price)}</button>`;}
export function renderShop(player){return `<section class="game-window">${heading('SẮM ĐỒ CHO BUỔI CÂU TIẾP THEO','Chợ bên bến',`${RODS.length} cần · ${BAITS.length} mồi · ${ACCESSORIES.length} phụ kiện · ${MAPS.length} vùng câu. Mua về kho nhà, rồi lắp hoặc bỏ vào túi tại Đồ nghề.`,`<span class="pill gold">${icon('coin')}${money(player.coins)} xu</span>`)}<div class="shop-tabs" aria-label="Nhóm hàng">${[['all','Tất cả'],['rod','Cần câu'],['bait','Mồi'],['accessory','Phụ kiện'],['bag','Túi đồ'],['map','Bản đồ']].map(([id,label])=>`<button data-shop-category="${id}" aria-pressed="${id==='all'}">${label}</button>`).join('')}</div><div id="shop-inventory" class="shop-inventory" data-filter="all">
 <section class="shop-section" data-category="rod"><h2>${icon('rod')} Cần & kỹ thuật</h2><div class="product-grid">${RODS.map(r=>`<article class="product"><div class="product-top"><span>${r.label}</span><span>${player.rods.includes(r.id)?'SỞ HỮU':'NÂNG CẤP'}</span></div><div class="product-icon">${toolArt('rod',r.id)}</div><h3>${r.name}</h3><p>${r.note}</p><div class="product-spec">Sức cần <b>${r.power.toFixed(1)}</b><span class="price">${r.price?money(r.price)+' xu':'Miễn phí'}</span></div>${shopStats(player,'rod',r)}${shopButton(player,'rod',r,player.rods.includes(r.id))}</article>`).join('')}</div></section>
 <section class="shop-section" data-category="bait"><h2>${icon('bag')} Mồi tự nhiên & mồi giả</h2><div class="product-grid">${BAITS.map(b=>`<article class="product"><div class="product-top"><span>${b.reusable?'DÙNG LẠI':b.amount+' PHẦN / GÓI'}</span><span>${b.reusable?(player.baits[b.id]?'ĐÃ CÓ':'CHƯA CÓ'):'CÓ '+(player.baits[b.id]||0)}</span></div><div class="product-icon">${toolArt('bait',b.id)}</div><h3>${b.name}</h3><p>${b.note}</p><div class="product-spec"><span class="price">${b.price?money(b.price)+' xu':'Đi kèm cần lure'}</span></div>${shopStats(player,'bait',b)}<p class="product-fit">Hợp: ${b.tech.map(t=>TECHNIQUES[t].label).join(' · ')}</p>${b.price?shopButton(player,'bait',b,b.reusable&&player.baits[b.id]>0):'<a class="button small" href="#rig">Chọn bộ lure</a>'}</article>`).join('')}</div></section>
 <section class="shop-section" data-category="accessory"><h2>${icon('bag')} Dây · Lưỡi · Phao · Máy · Vợt</h2>${Object.entries(ACCESSORY_SLOTS).map(([slot,label])=>`<h3 class="accessory-group-title">${label}</h3><div class="product-grid">${ACCESSORIES.filter(a=>a.slot===slot).map(a=>`<article class="product"><div class="product-top"><span>${label}</span><span>${player.accessories.includes(a.id)?'SỞ HỮU':'NÂNG CẤP'}</span></div><div class="product-icon">${toolArt('accessory',a.id)}</div><h3>${a.name}</h3><p>${a.effect}</p><div class="product-spec"><span class="price">${a.price?money(a.price)+' xu':'Đi kèm bộ khởi đầu'}</span></div>${a.assetKey?`<button class="small" data-line-detail="${a.id}">Xem cuộn cước & thông số</button>`:''}${shopStats(player,'accessory',a)}${shopButton(player,'accessory',a,player.accessories.includes(a.id))}</article>`).join('')}</div>`).join('')}</section>
 <section class="shop-section" data-category="bag"><h2>${icon('bag')} Túi mang đồ câu</h2><div class="product-grid">${Object.values(BAG_TYPES).map(b=>`<article class="product"><div class="product-top"><span>TÚI ĐỒ</span><span>${(player.systems?.bags||['cloth']).includes(b.id)?'SỞ HỮU':'NÂNG CẤP'}</span></div><div class="product-icon">${toolArt('bag',b.id)}</div><h3>${b.name}</h3><p>${b.note}</p><div class="product-spec">${b.rods} cần · ${b.baitTypes} loại mồi · ${b.accessorySlots} đồ dự phòng</div>${shopStats(player,'bag',b)}${shopButton(player,'bag',b,(player.systems?.bags||['cloth']).includes(b.id))}</article>`).join('')}</div></section>
 <section class="shop-section" data-category="map"><h2>${icon('pin')} Những góc bờ mới</h2><div class="product-grid">${MAPS.map(m=>`<article class="product map-product" data-map-product="${m.id}"><div class="product-map-art">${mapArt(m.id)}<span class="water-tag">${m.water}</span></div><h3>${m.name}</h3><p>${m.caption}. ${FISH.filter(f=>f.maps.includes(m.id)).length} loài cá. Gợi ý: ${TECHNIQUES[m.recommended].label.toLocaleLowerCase('vi')}.</p><div class="product-spec"><span class="price">${m.price?money(m.price)+' xu':'Bến khởi đầu miễn phí'}</span></div>${shopButton(player,'map',m,player.maps.includes(m.id))}${player.maps.includes(m.id)?`<button data-travel="${m.id}" class="small">Ra câu ${icon('arrow')}</button>`:''}</article>`).join('')}</div></section></div><div class="shop-free">${icon('leaf')}<p>Hết xu? Về bàn đồ đào giun miễn phí.</p><a class="button small" href="#rig">Về đồ nghề ${icon('arrow')}</a></div></section>`;}
export function renderPrepare(player,game,warning){
 const rod=game.rod,bait=getBait(player.bait),stats=game.stats;
 const departure=player.systems?.flags?.inventory===false?{ok:true}:validateDeparture(player);
 const error=rigError(player)||(!departure.ok?departure.reason:'')||(!bait.reusable&&!player.baits[player.bait]?'Đã hết mồi. Mua thêm ở Chợ bến hoặc đào giun tại Đồ nghề.':'');
 return `${warningHTML(warning)}<section class="game-window prepare-window">${heading('CHUẨN BỊ TRƯỚC KHI RA BỜ','Một buổi đi câu','Chọn chỗ ngồi, mang bộ cần hợp ý. Vào bờ rồi chỉ việc nhìn phao và giữ nhịp.',`<a class="button small" href="#home">${icon('back')} Về nhà</a>`)}
 <div class="prepare-layout"><section class="prepare-destination"><div class="prepare-map-intro"><div><span class="water-tag">${game.map.water}</span><h2 id="prepare-map-heading">${game.map.name}</h2><p>${game.map.caption}</p></div><button data-open-maps class="small">${icon('pin')} Đổi vùng</button></div><div class="prepare-landscape ${game.map.id==='AO'?'ao-lang-overview integrated-overview':''}"><img src="${game.map.background}" alt="Bản đồ ${game.map.name}: ${game.map.caption}">${game.map.id==='AO'?game.map.spots.map((spot,i)=>`<button class="map-hotspot ${spot.id}" data-spot="${i}" aria-label="Chọn ${spot.name}" aria-pressed="${i===game.spot}" ${game.busy?'disabled':''}><span>${spot.name}</span></button>`).join(''):''}</div>
 <div class="prepare-spots"><h3>Chọn vị trí câu</h3><p class="hint-note">${game.map.id==='AO'?'Chạm điểm trên bản đồ hoặc chọn chỗ ngồi bên dưới.':'Chọn một góc bờ hợp ý bên dưới.'}</p><div class="prepare-spot-list">${game.map.spots.map((spot,i)=>`<button data-spot="${i}" aria-pressed="${i===game.spot}" ${game.busy?'disabled':''}>${icon('pin')}<span><strong>${spot.name}</strong><small>Sâu ${spot.depth.toFixed(1)} m</small></span>${i===game.spot?icon('check'):''}</button>`).join('')}</div><details class="prepare-notes"><summary>Gợi ý tại điểm này</summary><p class="hint-note">Hợp ${TECHNIQUES[game.map.recommended].label.toLocaleLowerCase('vi')}. Có ${FISH.filter(f=>f.maps.includes(player.map)).length} loài để khám phá. Nguy cơ mắc đáy với bộ hiện tại: ${Math.round(snagChance(game.map,game.spot,player.rig.depth,rod.tech)*100)}% mỗi lượt.</p></details></div></section>
 <section class="prepare-loadout"><div class="prepare-gear-heading"><div><p class="eyebrow">MANG GÌ RA BỜ?</p><h2>Bộ câu của bạn</h2></div>${toolArt('rod',rod.id)}</div>
 <label for="prep-rod">Cần & kỹ thuật</label><select id="prep-rod" ${game.busy?'disabled':''}>${RODS.filter(r=>player.rods.includes(r.id)).map(r=>`<option value="${r.id}" ${r.id===player.rod?'selected':''}>${r.name} · ${r.label}</option>`).join('')}</select>
 <label for="prep-bait">Mồi mang theo</label><select id="prep-bait" aria-describedby="prep-bait-note" ${game.busy?'disabled':''}>${BAITS.filter(b=>acceptsBait(rod,b)&&(!b.reusable||player.baits[b.id]>0)).map(b=>`<option value="${b.id}" ${b.id===player.bait?'selected':''}>${b.name} · ${b.reusable?'Dùng lại':(player.baits[b.id]||0)+' phần'}</option>`).join('')}</select><p id="prep-bait-note" class="hint-note">${bait.note}</p>
 <dl class="prepare-stats"><div><dt>Tầng mồi</dt><dd>${rod.tech==='lure'?'Thu mồi':player.rig.depth.toFixed(1)+' m'}</dd></div><div><dt>Sức bộ cần</dt><dd>${stats.power.toFixed(1)}</dd></div><div><dt>${usesFloat(rod)?'Phao':'Tín hiệu'}</dt><dd>${usesFloat(rod)?game.float.visibleMarks+' vạch':'Đầu cần & dây'}</dd></div></dl>
 <div class="prepare-accessories">${Object.entries(ACCESSORY_SLOTS).filter(([slot])=>slot==='reel'?usesReel(rod):slot==='float'?usesFloat(rod):true).map(([slot,label])=>`<span><b>${label}</b>${slotItem(player,slot).name}</span>`).join('')}</div>
 <a class="button prepare-rig-link" href="#rig">${icon('bag')} Chỉnh đồ nghề ${icon('arrow')}</a><button data-open-keepnet class="prepare-keepnet">${icon('fish')} ${getContainer(player.container).name} · ${player.keptFish.length} con</button></section></div>
 ${bagSummary(player,game)}<div class="prepare-launch"><div><strong>${player.pending?'Bạn còn cá vừa lên bờ':error?'Bộ câu cần chỉnh lại':'Đã sẵn sàng ra bờ'}</strong><p id="prepare-ready">${player.pending?'Cho vào rọ hoặc thả cá trước lượt tiếp theo.':error||`${game.spotData.name} · ${rod.name} · ${bait.name}. Tạm dừng bất cứ lúc nào.`}</p></div><button class="primary" id="start-fishing" aria-describedby="prepare-ready" ${error&&!player.pending?'disabled':''}>${icon(player.pending?'fish':'play')}${player.pending?'Xem cá vừa câu':'Bắt đầu đi câu'}</button></div></section>`;
}
export function renderFishing(player,game,warning){return `<section class="fishing-layout" aria-label="Chế độ Đi câu"><div class="scene" data-map="${player.map}" data-phase="${game.phase}" data-assist="${player.settings.assist}" data-loading="${game.spotData.video?'loading':'ready'}">${game.spotData.video?`<video class="scene-bg scene-video" data-src="${game.spotData.video}" muted loop playsinline preload="none" aria-label="${game.map.name} · ${game.spotData.name}"></video>`:`<img class="scene-bg" src="${game.map.background}" alt="${game.map.name}: ${game.map.caption}">`}<canvas id="water" role="img" aria-label="Cảnh câu cá, cần, dây và tín hiệu. Điều khiển bằng các nút phía dưới hoặc Space + W A S D và phím lên, xuống."></canvas><div id="world-float" class="world-float" hidden aria-hidden="true"><i class="float-stem"></i><i class="float-body"></i><i class="float-ripple"></i><i class="bait-shadow"></i></div><div class="scene-vignette"></div>
 <header class="fishing-topbar"><button class="focus-back" id="leave-fishing" aria-label="Về nhà">${icon('back')}<span>Về nhà</span></button><div class="location-hud"><h1 id="map-heading">${game.map.name}</h1><p id="map-description">${game.spotData.name}</p></div><div class="session-hud" title="${player.settings.deadline?'Giờ về nhà':'Thời gian câu'}">${icon('clock')}<span id="timer-label" class="sr-only">${player.settings.deadline?'Giờ về nhà':'Thời gian câu'}</span><strong id="session-clock" class="num">00:00</strong></div><div class="scene-tools"><button class="icon-button" id="sound-toggle" aria-label="${player.settings.sound?'Tắt âm thanh':'Bật âm thanh'}" aria-pressed="${player.settings.sound}">${icon(player.settings.sound?'sound':'muted')}</button><button class="icon-button" id="help" aria-label="Thông tin buổi câu">${icon('info')}</button><button class="icon-button" id="pause" aria-label="Tạm dừng buổi câu" aria-pressed="${game.paused}">${icon('pause')}</button></div></header>
 <div class="scene-caption" hidden><strong id="spot-name">${game.spotData.name}</strong><span id="spot-depth">Sâu ${game.spotData.depth.toFixed(1)} m</span><span id="tech-label">${game.rod.label}</span><span class="focus-bait">${getBait(player.bait).name} · <b id="bank-count">${getBait(player.bait).reusable?'Dùng lại':(player.baits[player.bait]||0)+' phần'}</b></span></div>
 <div class="float-zoom" id="float-zoom"><div class="float-zoom-title" id="signal-title">${usesFloat(game.rod)?'PHAO CÂU':'ĐẦU CẦN & DÂY'}</div><div id="float-detail" ${usesFloat(game.rod)?'':'hidden'}>${floatSVG()}</div><svg id="tip-detail" viewBox="0 0 100 100" ${usesFloat(game.rod)?'hidden':''} aria-hidden="true"><path id="tip-rod" d="M12 90Q28 55 78 12" fill="none" stroke="#b99a59" stroke-width="5"/><path id="tip-line" d="M78 12 88 90" fill="none" stroke="#678776" stroke-width="2"/></svg><span id="float-label">${usesFloat(game.rod)?'Cận cảnh phao':'Đầu cần thả lỏng'}</span></div>
 ${warning?`<div class="focus-save-warning">${warningHTML(warning)}</div>`:''}
 <aside id="quiet-fishing-note" class="quiet-fishing-note" hidden role="status"><strong>Cá chưa cắn</strong><p>Vị trí, mồi hoặc nhịp cá hôm nay có thể chưa hợp. Mồi vẫn dưới nước.</p><div><button id="quiet-more" class="small">Xem gợi ý</button><button id="quiet-wait" class="small">Chờ thêm</button></div></aside>
 <div class="scene-bottom"><div class="status-box"><span class="status-gem" aria-hidden="true"></span><div><span id="status-title">Sẵn sàng</span><span id="status-copy">${esc(game.message)}</span></div></div>
 <div class="phase-track" aria-label="Các bước của lượt câu">${['Thả','Chờ','Giật','Dẫn','Lên bờ'].map((s,i)=>`<span data-phase-step="${i}"><i>${i+1}</i>${s}</span>`).join('')}</div>
 <div class="fight" id="fight" hidden><div class="meter-head"><strong id="fight-title">BÁM CÁ · GIỮ LỰC</strong><span id="tension-value" class="num">44% lực căng</span></div><div class="tension-track" style="--safe-min:${FIGHT_ZONE.min}%;--safe-max:${FIGHT_ZONE.max}%;--danger-min:${FIGHT_ZONE.red}%" role="meter" aria-label="Lực căng dây" aria-valuemin="0" aria-valuemax="100" aria-valuenow="44"><i class="tension-marker" id="tension-marker"></i></div><p id="fight-hint">Tay trái bám cá, tay phải chỉnh lực.</p><div class="meter-head"><span id="progress-label">Đưa cá lên bờ</span><span id="progress-value" class="num">0%</span></div><div class="energy-track" role="progressbar" aria-label="Tiến độ đưa cá lên bờ" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><i id="progress-bar"></i></div></div>
 <div class="water-controls"><button class="primary" id="cast">${icon('rod')}<span id="cast-label">Thả câu</span><span class="key">Space</span></button><button id="retrieve" disabled>${icon('arrow')}<span id="retrieve-label">Thu cần</span></button><button id="ease" hidden>${icon('wave')}Nhả hai tay</button></div></div>
 <div class="hand-panel left-hand"><div class="hand-heading"><span>TAY TRÁI</span><strong id="tracking-value">Bám theo cá</strong></div><button id="track-pad" class="track-pad" aria-label="Tay trái: giữ và di chuyển theo dấu cá" aria-describedby="track-note" disabled><span class="pad-grid" aria-hidden="true"></span><span id="fish-target" class="fish-target" aria-hidden="true">${icon('fish')}</span><span id="aim-reticle" class="aim-reticle" aria-hidden="true"></span><span class="pad-idle">Giữ & bám cá</span></button><p id="track-note">Di chuyển trái / phải / lên / xuống</p></div>
 <div class="hand-panel right-hand"><div class="hand-heading"><span>TAY PHẢI</span><strong id="force-value">Giữ cần</strong></div><button id="strike" class="rod-pad" aria-pressed="false" aria-describedby="rod-control-note" disabled><span class="force-scale" aria-hidden="true"><i id="force-fill"></i><b id="force-knob"></b></span><span class="force-top">TĂNG LỰC</span><span id="rod-label">Giữ để giật</span><span class="force-bottom">NỚI CẦN</span></button><p id="rod-control-note">Giữ + kéo lên / xuống để chỉnh lực</p></div>
 <div class="dual-instruction">Chuột bám cá + giữ Space, ↑ ↓ chỉnh lực · Hoặc W A S D bám cá + chuột giữ cần</div>
 <div class="session-end" id="session-end" hidden><p>Đến giờ về nhà. Bắt đầu buổi mới khi bạn sẵn sàng.</p><button class="primary" id="new-session">${icon('play')} Buổi câu mới</button></div>
 <div class="map-loading" id="map-loading" ${game.spotData.video?'':'hidden'} role="status" aria-live="polite"><div class="map-loading-card"><span class="loading-mark" aria-hidden="true">${icon('rod')}</span><p class="eyebrow">XÁCH CẦN RA BỜ</p><h2 id="map-load-title">Đang đến ${game.spotData.name}</h2><p id="map-load-copy">Chờ cảnh bờ nước tải xong. Cá chưa tính giờ đâu!</p><progress id="map-load-progress" max="100" aria-label="Tiến độ tải điểm câu"></progress><p id="map-load-status">Đang tải cảnh câu…</p><div class="loading-actions"><button id="map-load-back">${icon('back')} Chọn lại điểm</button><button class="primary" id="map-load-retry" hidden>Thử lại</button></div></div></div></div></section>`;}
